// This file is part of midnight-indexer.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Applies real transactions to a matching genesis ledger state. Fixtures
//! regenerated by `just generate-txs`.

use chain_indexer::domain::{LedgerState, node};
use criterion::{Criterion, black_box, criterion_group, criterion_main};
use indexer_common::{
    domain::{
        BlockHash, ByteVec, LedgerVersion, ProtocolVersion, TransactionHash,
        ledger::Transaction as LedgerTransaction,
    },
    infra::ledger_db,
};
use std::fs;
use tokio::runtime::Runtime;

fn init_ledger_db(rt: &Runtime) -> tempfile::TempDir {
    let temp_dir = tempfile::tempdir().expect("create tempdir");
    let sqlite_file = temp_dir
        .path()
        .join("ledger-db.sqlite")
        .display()
        .to_string();

    rt.block_on(async {
        ledger_db::init(ledger_db::Config {
            cache_max_nodes: 1_024,
            cnn_url: sqlite_file,
        })
        .await
        .expect("init ledger_db");
    });

    temp_dir
}

fn make_regular_tx(raw_bytes: Vec<u8>) -> node::RegularTransaction {
    let raw: ByteVec = raw_bytes.into();

    let deserialized = LedgerTransaction::deserialize(&raw, LedgerVersion::V9)
        .expect("deserialize fixture transaction");
    let hash: TransactionHash = deserialized.hash();
    let identifiers = deserialized.identifiers().expect("identifiers");

    node::RegularTransaction {
        hash,
        protocol_version: ProtocolVersion::V2_0(2_000_000),
        raw,
        identifiers,
        contract_actions: vec![],
    }
}

fn read_fixture(name: &str) -> Vec<u8> {
    fs::read(format!(
        "{}/../indexer-common/tests/{name}",
        env!("CARGO_MANIFEST_DIR")
    ))
    .unwrap_or_else(|e| panic!("read {name}: {e}"))
}

fn bench_apply_real_tx(c: &mut Criterion) {
    let rt = Runtime::new().expect("tokio runtime");
    let _temp_dir = init_ledger_db(&rt);

    let genesis_bytes = read_fixture("genesis_state.raw");
    let tx_1_2_2 = read_fixture("tx_1_2_2.raw");
    let tx_1_2_3 = read_fixture("tx_1_2_3.raw");

    let parent_block_hash = BlockHash::from([0u8; 32]);
    // Must fit the fixtures' validity windows; adjust on regen. The intent TTL
    // allows [generation, generation + 14d], but the dust spend is tighter: the
    // dust ctime must lie in [block_timestamp - 3h, block_timestamp], so pick a
    // timestamp within ~3h after `just generate-txs` ran.
    let block_timestamp: u64 = 1_780_525_000_000;
    let parent_block_timestamp: u64 = block_timestamp - 6_000;

    let mut group = c.benchmark_group("LedgerState::apply_transactions");

    group.bench_function("tx_1_2_2 on genesis (1-tx block)", |b| {
        b.iter_batched(
            || {
                let state = LedgerState::from_genesis(&genesis_bytes, LedgerVersion::V9)
                    .expect("from_genesis");
                let tx = make_regular_tx(tx_1_2_2.clone());
                (state, tx)
            },
            |(mut state, tx)| {
                state
                    .apply_transactions(
                        [node::Transaction::Regular(black_box(tx))],
                        black_box(parent_block_hash),
                        black_box(block_timestamp),
                        black_box(parent_block_timestamp),
                        black_box(true),
                    )
                    .expect("apply")
            },
            criterion::BatchSize::SmallInput,
        )
    });

    group.bench_function("tx_1_2_2 + tx_1_2_3 on genesis (2-tx block)", |b| {
        b.iter_batched(
            || {
                let state = LedgerState::from_genesis(&genesis_bytes, LedgerVersion::V9)
                    .expect("from_genesis");
                let txs = [
                    node::Transaction::Regular(make_regular_tx(tx_1_2_2.clone())),
                    node::Transaction::Regular(make_regular_tx(tx_1_2_3.clone())),
                ];
                (state, txs)
            },
            |(mut state, txs)| {
                state
                    .apply_transactions(
                        black_box(txs),
                        black_box(parent_block_hash),
                        black_box(block_timestamp),
                        black_box(parent_block_timestamp),
                        black_box(true),
                    )
                    .expect("apply")
            },
            criterion::BatchSize::SmallInput,
        )
    });

    group.finish();
}

criterion_group!(benches, bench_apply_real_tx);
criterion_main!(benches);
