fail_fast: true

exclude: |
  (?x)^(
    .*/(snapshots)/.*|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-toml
      - id: check-json

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false # This makes it a lot faster

      - id: cargo-clippy
        name: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo clippy --workspace --all-targets --offline -- -D warnings