[toolchain]
channel = "1.86"
components = [ "rust-src", "rustfmt", "clippy", "llvm-tools-preview", "rust-analyzer" ]
targets = [ "wasm32-unknown-unknown", "aarch64-unknown-linux-gnu"]
profile = "default"
