[workspace]
resolver = "2"
members = [
    "indexer-common",
    "chain-indexer",
    "wallet-indexer",
    "indexer-api",
    "indexer-standalone",
    "indexer-tests",
]

[workspace.package]
version       = "3.0.0"
edition       = "2024"
license       = "Apache-2.0"
readme        = "README.md"
homepage      = "https://github.com/midnightntwrk/midnight-indexer"
repository    = "https://github.com/midnightntwrk/midnight-indexer"
documentation = "https://github.com/midnightntwrk/midnight-indexer"
publish       = false

[workspace.dependencies]
anyhow                       = { version = "1.0" }
assert_matches               = { version = "1.5" }
async-graphql                = { version = "7.0" }
async-graphql-axum           = { version = "7.0" }
async-nats                   = { version = "0.42" }
async-stream                 = { version = "0.3" }
axum                         = { version = "0.8" }
bech32                       = { version = "0.11" }
bip32                        = { version = "0.5" }
byte-unit                    = { version = "5.1" }
byte-unit-serde              = { version = "0.1" }
chacha20poly1305             = { version = "0.10" }
clap                         = { version = "4.5" }
const-hex                    = { version = "1.15" }
derive_more                  = { version = "2.0" }
drop-stream                  = { version = "0.3" }
fake                         = { version = "2.10" }
fastrace                     = { version = "0.7" }
fastrace-axum                = { version = "0.1" }
fastrace-opentelemetry       = { version = "0.13" }
figment                      = { version = "0.10" }
fs_extra                     = { version = "1.3" }
futures                      = { version = "0.3" }
graphql_client               = { version = "0.14" }
humantime-serde              = { version = "1.1" }
indoc                        = { version = "2.0" }
itertools                    = { version = "0.14" }
log                          = { version = "0.4" }
logforth                     = { version = "0.27" }
metrics                      = { version = "0.24" }
metrics-exporter-prometheus  = { version = "0.17", default-features = false }
midnight-base-crypto_v6      = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-base-crypto", tag = "ledger-6.0.0-alpha.3" }
midnight-coin-structure_v6   = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-coin-structure", tag = "ledger-6.0.0-alpha.3" }
midnight-ledger_v6           = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-ledger", tag = "ledger-6.0.0-alpha.3" }
midnight-onchain-runtime_v6  = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-onchain-runtime", tag = "ledger-6.0.0-alpha.3" }
midnight-serialize_v6        = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-serialize", tag = "ledger-6.0.0-alpha.3" }
midnight-storage_v6          = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-storage", tag = "ledger-6.0.0-alpha.3" }
midnight-transient-crypto_v6 = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-transient-crypto", tag = "ledger-6.0.0-alpha.3" }
midnight-zswap_v6            = { git = "https://github.com/midnightntwrk/midnight-ledger", package = "midnight-zswap", tag = "ledger-6.0.0-alpha.3" }
nix                          = { version = "0.30" }
opentelemetry                = { version = "0.30" }
opentelemetry-otlp           = { version = "0.30" }
opentelemetry_sdk            = { version = "0.30" }
parity-scale-codec           = { version = "3.7" }
parking_lot                  = { version = "0.12" }
paste                        = { version = "1.0" }
reqwest                      = { version = "0.12", default-features = false }
secrecy                      = { version = "0.10" }
serde                        = { version = "1.0" }
serde_json                   = { version = "1.0" }
serde_with                   = { version = "3.14" }
sha2                         = { version = "0.10" }
sqlx                         = { version = "0.8" }
stream-cancel                = { version = "0.8" }
subxt                        = { version = "0.44" }
tempfile                     = { version = "3.22" }
testcontainers               = { version = "0.25" }
testcontainers-modules       = { version = "0.13" }
thiserror                    = { version = "2.0" }
tokio                        = { version = "1" }
tokio-stream                 = { version = "0.1" }
tokio-tungstenite            = { version = "0.27" }
tokio-util                   = { version = "0.7" }
tower                        = { version = "0.5" }
tower-http                   = { version = "0.6" }
trait-variant                = { version = "0.1" }
uuid                         = { version = "1.18" }
