// This file is part of midnightntwrk/midnight-indexer
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Integration tests for the top-level Contract type and contract(address, offset)
// query (#1275): the contract as the topmost concept, with point-in-time state,
// maintenance authority, and a bounded recent-actions sub-query. This is distinct
// from the pre-existing contractAction(address, offset) query (contract *actions*
// as topmost), which is covered separately in contract-queries.test.ts.
//
// The whole surface is @beta: it ships on the 4.4 line (devnet/stagenet) but not
// on pre-4.4 environments, so the file gates on surface presence. The
// contract-address fixture (contract-actions.jsonc, generated by
// qa/tools/block-scanner) supplies a real contract; cases needing it skip where
// it is not provisioned. The ECDSA maintenance-key variant has no test data on
// current environments and is left as a todo.
//
// Tracking: https://github.com/midnightntwrk/midnight-indexer/issues/1275

import log from '@utils/logging/logger';
import { env } from 'environment/model';
import type { TestContext } from 'vitest';
import '@utils/logging/test-logging-hooks';
import { IndexerHttpClient } from '@utils/indexer/http-client';
import dataProvider from '@utils/testdata-provider';

const httpClient = new IndexerHttpClient();

const HEX = /^[0-9a-f]+$/;
// A block that predates any contract deployment, for the as-of negative case.
const EARLY_BLOCK = 1;

let surfacePresent = false;
let knownContract: string | null = null;

describe.skipIf(env.isUndeployedEnv())('contract type queries', () => {
  beforeAll(async () => {
    // Probe with a valid-format address that does not exist: a healthy response
    // (null contract) means the surface is present; a GraphQL error means the
    // deployed indexer predates the @beta contract() query.
    const probe = await httpClient.getContract(dataProvider.getNonExistingContractAddress());
    if (probe.errors || probe.data === undefined) {
      log.warn(`contract() query not present on ${env.getCurrentEnvironmentName()}; skipping`);
      return;
    }
    surfacePresent = true;

    try {
      knownContract = dataProvider.getKnownContractAddress();
    } catch (error) {
      log.warn(
        `No known contract fixture for ${env.getCurrentEnvironmentName()}: ${String(error)}`,
      );
      knownContract = null;
    }
  }, 30_000);

  describe('a contract query by address', () => {
    /**
     * @given a contract known to exist on the chain
     * @when contract(address) is queried without an offset
     * @then the Contract resolves with its address, a hex-encoded state, a
     *       maintenance authority, and a recent-actions list
     */
    test('should return the contract with state, maintenance authority and actions', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'State'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const response = await httpClient.getContract(knownContract);

      expect(response).toBeSuccess();
      const contract = response.data!.contract;
      expect(contract).not.toBeNull();
      expect(contract!.address).toBe(knownContract);
      expect(contract!.state).toMatch(HEX);
      expect(contract!.maintenanceAuthority).toBeDefined();
      expect(Array.isArray(contract!.actions)).toBe(true);
    });

    /**
     * @given a valid-format contract address that does not exist on the chain
     * @when contract(address) is queried
     * @then the query resolves to null
     */
    test('should return null for a non-existent contract', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'Negative'] };
      if (!surfacePresent) return ctx.skip();

      const response = await httpClient.getContract(dataProvider.getNonExistingContractAddress());

      expect(response).toBeSuccess();
      expect(response.data!.contract).toBeNull();
    });

    /**
     * @given a set of malformed-format contract addresses
     * @when contract(address) is queried for each
     * @then the indexer rejects every one with a GraphQL error
     */
    test('should error for malformed contract addresses', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'Negative'] };
      if (!surfacePresent) return ctx.skip();

      for (const malformedAddress of dataProvider.getFabricatedMalformedContractAddresses()) {
        const response = await httpClient.getContract(malformedAddress);
        // A malformed address is rejected as a GraphQL error, surfacing either as
        // a variable-coercion error (no data) or a field-level error, so assert on
        // the presence of an error rather than the whole-response shape.
        expect
          .soft(
            response.errors ?? [],
            `expected a GraphQL error for malformed address ${malformedAddress}`,
          )
          .not.toHaveLength(0);
      }
    });
  });

  describe('the maintenance authority', () => {
    /**
     * @given a contract known to exist
     * @when its maintenanceAuthority is read
     * @then threshold and counter are non-negative integers and every committee
     *       member has a valid kind (SCHNORR or ECDSA) and a hex-encoded key
     */
    test('should expose a committee of valid verifying keys with threshold and counter', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'MaintenanceAuthority'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const response = await httpClient.getContract(knownContract);
      expect(response).toBeSuccess();
      const authority = response.data!.contract!.maintenanceAuthority;

      expect(Number.isInteger(authority.threshold)).toBe(true);
      expect(authority.threshold).toBeGreaterThanOrEqual(0);
      expect(Number.isInteger(authority.counter)).toBe(true);
      expect(authority.counter).toBeGreaterThanOrEqual(0);
      for (const key of authority.committee) {
        expect(['SCHNORR', 'ECDSA']).toContain(key.kind);
        expect(key.key).toMatch(HEX);
      }
    });

    // ECDSA committee members have no test data on the current environments; the
    // deployed contracts use Schnorr keys. Cover the ECDSA mapping explicitly
    // once a contract with an ECDSA maintenance key exists in a test env.
    test.todo('should map an ECDSA committee verifying key');
  });

  describe('the actions sub-query', () => {
    /**
     * @given a contract known to exist with at least one action
     * @when actions(limit: 1) is requested
     * @then at most one action is returned
     */
    test('should bound the actions list by limit', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'Actions'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const response = await httpClient.getContract(knownContract, { actionsLimit: 1 });
      expect(response).toBeSuccess();
      expect(response.data!.contract!.actions.length).toBeLessThanOrEqual(1);
    });

    /**
     * @given a contract known to exist (the fixture requires a Deploy action)
     * @when actions(type: DEPLOY) is requested
     * @then every returned action is a ContractDeploy for that contract
     */
    test('should filter actions by type DEPLOY', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'Actions'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const response = await httpClient.getContract(knownContract, { actionsType: 'DEPLOY' });
      expect(response).toBeSuccess();
      const actions = response.data!.contract!.actions;
      expect(actions.length).toBeGreaterThanOrEqual(1);
      for (const action of actions) {
        expect(action.__typename).toBe('ContractDeploy');
        expect(action.address).toBe(knownContract);
      }
    });

    /**
     * @given a contract known to exist that has at least one Call action
     * @when actions(type: CALL) is requested
     * @then every returned action is a ContractCall for that contract
     */
    test('should filter actions by type CALL', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'Actions'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const response = await httpClient.getContract(knownContract, { actionsType: 'CALL' });
      expect(response).toBeSuccess();
      const actions = response.data!.contract!.actions;
      expect(actions.length).toBeGreaterThanOrEqual(1);
      for (const action of actions) {
        expect(action.__typename).toBe('ContractCall');
        expect(action.address).toBe(knownContract);
      }
    });

    // No contract with a ContractUpdate (maintenance) action exists on the
    // current validation environments; the fixtures carry only Deploy and Call
    // actions. Cover the UPDATE filter once such data is available.
    test.todo('should filter actions by type UPDATE');
  });

  describe('point-in-time state via offset', () => {
    /**
     * @given a contract known to exist and the latest block pinned by hash
     * @when contract(address, offset: { hash }) is queried
     * @then the contract resolves with a hex-encoded state as of that block
     */
    test('should return state as of a pinned block hash', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'State', 'ByHash'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const latest = await httpClient.getLatestBlock();
      expect(latest).toBeSuccess();
      const hash = latest.data!.block!.hash;

      const response = await httpClient.getContract(knownContract, { offset: { hash } });
      expect(response).toBeSuccess();
      expect(response.data!.contract).not.toBeNull();
      expect(response.data!.contract!.state).toMatch(HEX);
    });

    /**
     * @given a contract known to exist and the latest block pinned by height
     * @when contract(address, offset: { height }) is queried
     * @then the contract resolves with a hex-encoded state as of that block,
     *       identical to the state read at the same block pinned by hash
     */
    test('should return state as of a pinned block height', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'State', 'ByHeight'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const latest = await httpClient.getLatestBlock();
      expect(latest).toBeSuccess();
      const { hash, height } = latest.data!.block!;

      const byHeight = await httpClient.getContract(knownContract, { offset: { height } });
      const byHash = await httpClient.getContract(knownContract, { offset: { hash } });

      expect(byHeight).toBeSuccess();
      expect(byHeight.data!.contract).not.toBeNull();
      expect(byHeight.data!.contract!.state).toMatch(HEX);
      expect(byHeight.data!.contract!.state).toBe(byHash.data!.contract!.state);
    });

    /**
     * @given a contract known to exist and a block that predates its deployment
     * @when contract(address, offset: { height: 1 }) is queried
     * @then the contract resolves to null (it did not exist as of that block)
     */
    test('should return null when queried at a block before the contract existed', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Contract', 'ByHeight', 'Negative'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const response = await httpClient.getContract(knownContract, {
        offset: { height: EARLY_BLOCK },
      });

      expect(response).toBeSuccess();
      expect(response.data!.contract).toBeNull();
    });
  });
});
