// This file is part of midnightntwrk/midnight-indexer
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Integration tests for Block.contractZswapState and the composed
// cross-contract-calls (CCC) execution-inputs read (#1304).
//
// contractZswapState is the global zswap commitment tree filtered to a single
// contract, resolved from a block's ledger state — nullable, null when the
// contract does not exist as of that block. It is a @beta field: the surface
// ships on the 4.4 line (devnet/stagenet) but not on pre-4.4 environments, so
// the whole file gates on surface presence and skips where it is absent. The
// contract-address fixture (contract-actions.jsonc, generated by
// qa/tools/block-scanner) supplies a real contract; cases needing it skip where
// it is not provisioned for the environment.
//
// Tracking: https://github.com/midnightntwrk/midnight-indexer/issues/1304

import log from '@utils/logging/logger';
import { env } from 'environment/model';
import type { TestContext } from 'vitest';
import '@utils/logging/test-logging-hooks';
import { IndexerHttpClient } from '@utils/indexer/http-client';
import dataProvider from '@utils/testdata-provider';

const httpClient = new IndexerHttpClient();

const HEX = /^[0-9a-f]+$/;

let surfacePresent = false;
let knownContract: string | null = null;

describe.skipIf(env.isUndeployedEnv())('contract zswap state queries', () => {
  beforeAll(async () => {
    // Probe with a valid-format address that does not exist: a healthy response
    // (null contractZswapState) means the surface is present; a GraphQL error
    // means the deployed indexer predates the @beta field.
    const probe = await httpClient.getBlockContractZswapState(
      dataProvider.getNonExistingContractAddress(),
    );
    if (probe.errors || !probe.data) {
      log.warn(`contractZswapState not present on ${env.getCurrentEnvironmentName()}; skipping`);
      return;
    }
    surfacePresent = true;

    try {
      knownContract = dataProvider.getKnownContractAddress();
    } catch (error) {
      log.warn(
        `No known contract fixture for ${env.getCurrentEnvironmentName()}: ${String(error)}`,
      );
      knownContract = null;
    }
  }, 30_000);

  describe('block.contractZswapState', () => {
    /**
     * @given a contract known to exist on the chain
     * @when block.contractZswapState is queried for that contract at the latest block
     * @then a non-empty hex-encoded zswap state is returned
     */
    test('should return the contract-filtered zswap state for a known contract', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Block', 'Contract', 'Zswap'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const response = await httpClient.getBlockContractZswapState(knownContract);

      expect(response).toBeSuccess();
      const state = response.data!.block!.contractZswapState;
      expect(state).not.toBeNull();
      expect(state).toMatch(HEX);
    });

    /**
     * @given a valid-format contract address that does not exist on the chain
     * @when block.contractZswapState is queried for that address
     * @then the field resolves to null (no such contract as of this block)
     */
    test('should return null for a non-existent contract', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Block', 'Contract', 'Zswap', 'Negative'] };
      if (!surfacePresent) return ctx.skip();

      const response = await httpClient.getBlockContractZswapState(
        dataProvider.getNonExistingContractAddress(),
      );

      expect(response).toBeSuccess();
      expect(response.data!.block!.contractZswapState).toBeNull();
    });

    /**
     * @given a contract known to exist and a fixed block pinned by hash
     * @when block.contractZswapState is queried twice at that same block
     * @then both queries return the identical state (deterministic at a block)
     */
    test('should return identical state for repeated queries pinned to the same block', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Block', 'Contract', 'Zswap', 'ByHash'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const latest = await httpClient.getLatestBlock();
      expect(latest).toBeSuccess();
      const hash = latest.data!.block!.hash;

      const first = await httpClient.getBlockContractZswapState(knownContract, { hash });
      const second = await httpClient.getBlockContractZswapState(knownContract, { hash });

      expect(first).toBeSuccess();
      expect(second).toBeSuccess();
      expect(second.data!.block!.contractZswapState).toBe(first.data!.block!.contractZswapState);
    });

    /**
     * @given a set of malformed-format contract addresses
     * @when block.contractZswapState is queried for each
     * @then the indexer rejects every one with a GraphQL error
     */
    test('should error for malformed contract addresses', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Block', 'Contract', 'Zswap', 'Negative'] };
      if (!surfacePresent) return ctx.skip();

      for (const malformedAddress of dataProvider.getFabricatedMalformedContractAddresses()) {
        const response = await httpClient.getBlockContractZswapState(malformedAddress);
        // A malformed address is rejected as a GraphQL error. Depending on the
        // input it surfaces either as a variable-coercion error (no data) or a
        // field-level error on the otherwise-resolved block, so assert on the
        // presence of an error rather than the whole-response shape.
        expect
          .soft(
            response.errors ?? [],
            `expected a GraphQL error for malformed address ${malformedAddress}`,
          )
          .not.toHaveLength(0);
      }
    });

    /**
     * @given a known contract and a set of malformed-format block hashes
     * @when block.contractZswapState is queried at each malformed hash offset
     * @then the indexer rejects every one with a GraphQL error
     */
    test('should error for a malformed block-hash offset', async (ctx: TestContext) => {
      ctx.task!.meta.custom = {
        labels: ['Query', 'Block', 'Contract', 'Zswap', 'ByHash', 'Negative'],
      };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      for (const malformedHash of dataProvider.getFabricatedMalformedHashes()) {
        const response = await httpClient.getBlockContractZswapState(knownContract, {
          hash: malformedHash,
        });
        expect.soft(response).toBeError();
      }
    });

    /**
     * @given a known contract and the latest block pinned by height
     * @when block.contractZswapState is queried at that height offset
     * @then a non-empty hex-encoded zswap state is returned, identical to the
     *       state read at the same block pinned by hash
     */
    test('should return the zswap state when the block is pinned by height', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Block', 'Contract', 'Zswap', 'ByHeight'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const latest = await httpClient.getLatestBlock();
      expect(latest).toBeSuccess();
      const { hash, height } = latest.data!.block!;

      const byHeight = await httpClient.getBlockContractZswapState(knownContract, { height });
      const byHash = await httpClient.getBlockContractZswapState(knownContract, { hash });

      expect(byHeight).toBeSuccess();
      const state = byHeight.data!.block!.contractZswapState;
      expect(state).not.toBeNull();
      expect(state).toMatch(HEX);
      expect(state).toBe(byHash.data!.block!.contractZswapState);
    });
  });

  describe('the composed execution-inputs query', () => {
    /**
     * @given a contract known to exist on the chain
     * @when the composed ExecutionInputs query (block { ledgerParameters,
     *       contractZswapState } + contract { state }) is issued
     * @then all three read anchored to one block are present: ledgerParameters
     *       and contractZswapState on the block, and the contract's state
     *
     * This is the CCC consumer pattern documented on the contractZswapState field.
     */
    test('should resolve zswap state, ledger parameters and contract state anchored to one block', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Block', 'Contract', 'Zswap'] };
      if (!surfacePresent) return ctx.skip();
      if (!knownContract) return ctx.skip(true, 'no known contract fixture on this env');

      const response = await httpClient.getExecutionInputs(knownContract);

      expect(response).toBeSuccess();
      const block = response.data!.block!;
      expect(block.hash).toMatch(HEX);
      expect(block.ledgerParameters).toMatch(HEX);
      expect(block.contractZswapState).not.toBeNull();
      expect(block.contractZswapState).toMatch(HEX);
      expect(response.data!.contract).not.toBeNull();
      expect(response.data!.contract!.state).toMatch(HEX);
    });

    /**
     * @given a valid-format contract address that does not exist
     * @when the composed ExecutionInputs query is issued
     * @then block.contractZswapState is null and contract is null, while the
     *       block itself still resolves with ledger parameters
     */
    test('should return null zswap state and null contract for a non-existent contract', async (ctx: TestContext) => {
      ctx.task!.meta.custom = { labels: ['Query', 'Block', 'Contract', 'Zswap', 'Negative'] };
      if (!surfacePresent) return ctx.skip();

      const response = await httpClient.getExecutionInputs(
        dataProvider.getNonExistingContractAddress(),
      );

      expect(response).toBeSuccess();
      expect(response.data!.block!.ledgerParameters).toMatch(HEX);
      expect(response.data!.block!.contractZswapState).toBeNull();
      expect(response.data!.contract).toBeNull();
    });
  });
});
