run_migrations: true

application:
  network_id: "Undeployed"
  blocks_buffer: 10
  save_ledger_state_after: 1000
  caught_up_max_distance: 10
  caught_up_leeway: 5

infra:
  storage:
    host: "localhost"
    port: 5432
    dbname: "indexer"
    user: "indexer"
    sslmode: "prefer"
    max_connections: 10
    idle_timeout: "1m"
    max_lifetime: "5m"

  pub_sub:
    url: "localhost:4222"
    username: "indexer"

  ledger_state_storage:
    url: "localhost:4222"
    username: "indexer"

  node:
    url: "ws://localhost:9944"
    genesis_protocol_version: 16000
    reconnect_max_delay: "10s" # 10ms, 100ms, 1s, 10s
    reconnect_max_attempts: 30 # Roughly 5m

telemetry:
  tracing:
    enabled: false
    service_name: "chain-indexer"
    otlp_exporter_endpoint: "http://localhost:4317"
  metrics:
    enabled: false
    address: "0.0.0.0"
    port: 9000
