name: 'Run Pytest Tests'
description: 'Activate Python virtual environment and run end-to-end tests'

inputs:
  env:
    description: 'Test environment'
    required: true
  keyword:
    description: 'Run tests by keyword (-k)'
    required: false
    default: 'test_'
  markers:
    description: 'Run tests by markers (-m)'
    required: false
  mc_epoch:
    description: 'MC epoch to test (committee tests)'
    required: false
  latest_mc_epoch:
    description: 'Parametrize committee tests to verify the whole last MC epoch'
    required: false
  deployment_mc_epoch:
    description: 'Deployment MC epoch'
    required: false
  log_level:
    description: 'Log CLI level'
    required: false
    default: 'info'
  init_timestamp:
    description: 'MC initialization timestamp in seconds'
    required: false
    default: '0'
  blockchain:
    description: 'Blockchain to test'
    required: true
  local-environment:
    description: 'Run tests in local environment (true or false)'
    required: false
    default: 'false'
  decrypt:
    description: 'Decrypt secrets'
    required: false
  threads:
    description: 'Number of threads to use'
    required: false
    default: '4'

runs:
  using: composite
  steps:
    - name: Run tests
      id: run-tests
      continue-on-error: true
      shell: bash
      env:
        MARKERS: ${{ inputs.markers }}
        MC_EPOCH: ${{ inputs.mc_epoch }}
        LATEST_MC_EPOCH: ${{ inputs.latest_mc_epoch }}
        DEPLOYMENT_MC_EPOCH: ${{ inputs.deployment_mc_epoch }}
        DECRYPT: ${{ inputs.decrypt }}
        BLOCKCHAIN: ${{ inputs.blockchain }}
        TEST_ENV: ${{ inputs.env }}
        LOG_LEVEL: ${{ inputs.log_level }}
        KEYWORD: ${{ inputs.keyword }}
        THREADS: ${{ inputs.threads }}
        INIT_TIMESTAMP: ${{ inputs.init_timestamp }}
        LOCAL_ENVIRONMENT: ${{ inputs.local-environment }}
      run: |
        markers_switch=""
        if [ -n "$MARKERS" ]; then
          markers_switch="-m '$MARKERS'"
        fi

        mc_epoch_switch=""
        if [ -n "$MC_EPOCH" ]; then
          mc_epoch_switch="--mc-epoch '$MC_EPOCH'"
        fi

        latest_mc_epoch_switch=""
        if [ "$LATEST_MC_EPOCH" = "true" ]; then
          latest_mc_epoch_switch="--latest-mc-epoch"
        fi

        deployment_mc_epoch_switch=""
        if [ -n "$DEPLOYMENT_MC_EPOCH" ]; then
          deployment_mc_epoch_switch="--deployment-mc-epoch '$DEPLOYMENT_MC_EPOCH'"
        fi

        decrypt_switch=""
        if [ "$DECRYPT" = "true" ]; then
          decrypt_switch="--decrypt"
        fi

        pytest_cmd="pytest --blockchain '$BLOCKCHAIN' \
          --env '$TEST_ENV' \
          --log-cli-level '$LOG_LEVEL' \
          -k '$KEYWORD' \
          ${markers_switch} \
          -n '$THREADS' \
          --dist=loadgroup \
          --ci-run \
          --init-timestamp '$INIT_TIMESTAMP' \
          ${mc_epoch_switch} \
          ${latest_mc_epoch_switch} \
          ${deployment_mc_epoch_switch} \
          ${decrypt_switch} \
          --json-report \
          --json-report-file=logs/.report.json \
          --json-report-summary \
          --junitxml=logs/junit_report.xml"

        if [[ "$LOCAL_ENVIRONMENT" == "true" ]]; then
          echo "Running tests via docker exec"
          docker exec tests bash -c "
            cd /e2e-tests &&
            source venv/bin/activate &&
            $pytest_cmd
          "
        else
          echo "Running tests locally"
          cd e2e-tests || exit 1
          source venv/bin/activate
          eval "$pytest_cmd"
        fi

    - name: Copy test results
      if: ${{ inputs.local-environment == 'true' }}
      shell: bash
      run: |
        echo "Copy test results from docker container"
        mkdir -p e2e-tests
        docker cp tests:/e2e-tests/logs e2e-tests

    - name: Upload test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
      with:
        name: test-results
        path: e2e-tests/logs
        overwrite: true
        if-no-files-found: error
        include-hidden-files: true

    - name: Fail the job
      if: ${{ steps.run-tests.outcome == 'failure' }}
      run: exit 1
      shell: bash
