name: build-indexer-tests

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest-16-core-x64
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up environment
        env:
          toolchain_toml: "rust-toolchain.toml"
        run: |
          toolchain=$(grep channel rust-toolchain.toml | sed -r 's/channel = "(.*)"/\1/')
          echo "toolchain=$toolchain" | tee -a $GITHUB_ENV
          version=$(grep '^version.*=' Cargo.toml | sed -E 's/version.*=.*"(.*)"/\1/')
          echo "version=$version" | tee -a $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_MIDNIGHTNTWRK_USER }}
          password: ${{ secrets.DOCKERHUB_MIDNIGHTNTWRK_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: MidnightCI
          password: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Prepare metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 8
        with:
          images: |
            ghcr.io/midnight-ntwrk/indexer-tests
            ${{ github.ref_type == 'tag' && 'midnightntwrk/indexer-tests' || '' }}
          tags: |
            type=semver,pattern={{version}}
            ${{ github.ref_type != 'tag' && format('type=sha,prefix={0}-,format=short', env.version) || '' }}
          labels: |
            org.opencontainers.image.source=https://github.com/midnightntwrk/midnight-indexer/
            org.opencontainers.image.title=indexer-tests
            org.opencontainers.image.description=Midnight Indexer Tests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: indexer-tests/Dockerfile
          push: true
          build-args: RUST_VERSION=${{env.toolchain}}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/midnight-ntwrk/indexer-tests:buildcache
          cache-to: type=registry,ref=ghcr.io/midnight-ntwrk/indexer-tests:buildcache,mode=max
