name: dependabot-approve-merge

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  toolchain:
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest-8-core-x64
    outputs:
      toolchain: ${{steps.set_toolchain.outputs.toolchain}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set toolchain
        id: set_toolchain
        env:
          toolchain_toml: "rust-toolchain.toml"
        run: |
          toolchain=$(grep channel rust-toolchain.toml | sed -r 's/channel = "(.*)"/\1/')
          echo "using toolchain $toolchain from rust-toolchain.toml"
          echo "toolchain=$toolchain" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest-8-core-x64
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs: toolchain
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: MidnightCI
          password: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{needs.toolchain.outputs.toolchain}}

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - uses: Swatinem/rust-cache@v2

      - name: just test
        run: |
          . ./.envrc
          git config --global url."https://@github.com".insteadOf "ssh://git@github.com"
          rustup override set ${{needs.toolchain.outputs.toolchain}}
          just feature=cloud test && just feature=standalone test
        env:
          APP__INFRA__STORAGE__PASSWORD: ${{ secrets.APP__INFRA__STORAGE__PASSWORD }}
          APP__INFRA__PUB_SUB__PASSWORD: ${{ secrets.APP__INFRA__PUB_SUB__PASSWORD }}
          APP__INFRA__LEDGER_STATE_STORAGE__PASSWORD: ${{ secrets.APP__INFRA__LEDGER_STATE_STORAGE__PASSWORD }}
          APP__INFRA__SECRET: ${{ secrets.APP__INFRA__SECRET }}

  dependabot-approve-merge:
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest-8-core-x64
    needs: test
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: merge
        run: gh pr merge --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
