name: Indexer QAIntegration Tests Base workflow

# Note this is the base workflow used by the other
# qa-integration-tests-<environment>.yml workflows

on:
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: Midnight target environment (nodedev01/devnet/qanet/testnet02)
        required: true
        default: qanet
        options:
          - nodedev01
          - qanet
          - devnet
          - testnet02
      ref:
        type: string
        description: Git ref
        required: false
        default: main
  workflow_call:
    inputs:
      target_env:
        type: string
        description: Midnight target environment (nodedev01/devnet/qanet/testnet02)
        required: true
        default: qanet
      ref:
        type: string
        description: Git ref
        required: false
    secrets:
      MIDNIGHTCI_PACKAGES_WRITE:
        required: true

concurrency:
  group: ${{github.workflow}}-${{github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  basic-integration-tests:
    env:
      TARGET_ENV: ${{ inputs.target_env }}
      GITHUB_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
      NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
    name: Execute basic integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Setup Node.js v22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            qa/tests/.yarn/cache
            qa/tests/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('qa/tests/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: qa/tests
        run: yarn install --immutable

      - name: Run integration tests
        working-directory: qa/tests
        run: yarn test

      - name: Upload Integration Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-reports
          path: ./qa/tests/reports/custom-junit-report.xml
          if-no-files-found: warn

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qa-integration-tests-${{ inputs.target_env }}-logs
          path: |
            ./qa/tests/logs

