name: Indexer QA Block Streaming Test (QAnet)

on:
  workflow_dispatch:
  schedule:
    # Every 30 minutes on workdays (Mon-Fri), covering UK and US working hours (07:00-21:00 UTC)
    - cron: '*/30 7-21 * * 1-5'

# no top level default permissions for security reasons
permissions:
  contents: read

jobs:
  test-block-subscriptions:
    name: Test Block Subscriptions
    uses: ./.github/workflows/qa-test-block-subscription-base-workflow.yml
    with:
      target_env: qanet
      indexer_api_version: v3
