name: rust-security-scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write # required for SARIF upload
  contents: read

jobs:
  rust-security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install cargo-audit
        run: cargo install --git https://github.com/rustsec/rustsec cargo-audit

      - name: Run cargo-audit
        run: cargo audit --format sarif | tee scan.sarif || true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@7273f08caa1dcf2c2837f362f1982de0ab4dc344
        with:
          sarif_file: scan.sarif

      - name: Install Deny
        run: cargo install cargo-deny

      - name: Run deny
        run: cargo deny check -Aduplicate -Aunmaintained -Alicense-not-encountered -Aparse-error -Asource-not-allowed -Aunlicensed
        # TODO: once everything's open sourced remove -Aunlicensed

      # TODO: Remove this checkout step once upload-sarif-github-action repo is made public
      - name: Checkout Upload action repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: midnightntwrk/upload-sarif-github-action
          ref: main
          path: upload-sarif-github-action
          token: ${{ secrets.MIDNIGHTCI_REPO }}

      - name: Upload SARIF to Checkmarx
        uses: ./upload-sarif-github-action
        with:
          sarif-file: scan.sarif
          project-name: midnightntwrk/midnight-indexer
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
