// This file is part of midnightntwrk/midnight-indexer
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The custom-unshielded-token sibling of night-transactions.test.ts: the same
// transfer scenario, against a contract-minted unshielded token instead of NIGHT.
// Both suites share every test through unshielded-transfer-scenario.ts, so the two
// token types cannot drift apart in coverage.
//
// It deliberately mirrors none of the NIGHT suite's dust tests: DUST is generated by
// holding NIGHT, so a custom unshielded token produces no dust events at all.
//
// A custom token is not on the chain from genesis — it has to be minted by a
// contract and put in the funding wallet. That provisioning is an environment
// concern, not something this suite does, so the suite skips (never fails) when the
// environment has not been provisioned:
//   * no candidate in data/static/<env>/unshielded-token-types.jsonc (the fixture
//     the block-scanner generates) -> the whole suite is skipped at collection;
//   * candidates exist but the funding wallet can spend none of them
//     -> every test skips with an "environment not provisioned" reason.
// The second case is the normal one to expect: the fixture records what was unspent
// at scan time, so its candidates can have been spent since.
// Minting the token from the test itself, through the toolkit minter flow the
// wrapper already implements (deployMintSendUnshielded), is a known future option
// and was deliberately deferred — it would make every run deploy a contract.

import log from '@utils/logging/logger';
import '@utils/logging/test-logging-hooks';
import dataProvider from '@utils/testdata-provider';
import {
  defineUnshieldedTransferTests,
  setupUnshieldedTransferScenario,
  UNSHIELDED_TRANSFER_TIMEOUT,
} from './unshielded-transfer-scenario';

const CANDIDATE_TOKEN_TYPES = dataProvider.getCustomUnshieldedTokenTypes();

// Destination wallets are numbered per e2e suite (…e2e001 is the NIGHT suite's) so that
// no two suites share one — see `destinationSeed` in unshielded-transfer-scenario.ts.
const DESTINATION_SEED = '0000000000000000000000000000000000000000000000000000000000e2e002';
const TRANSFER_AMOUNT = 1;

describe.skipIf(CANDIDATE_TOKEN_TYPES.length === 0)(
  'unshielded custom token transactions',
  { timeout: UNSHIELDED_TRANSFER_TIMEOUT },
  () => {
    const scenario = setupUnshieldedTransferScenario({
      label: 'CustomToken',
      // Placeholder: `prepare` below replaces it with the candidate the funding wallet
      // can actually spend. Indexing is safe — the describe is skipped when there is
      // no candidate at all.
      tokenType: CANDIDATE_TOKEN_TYPES[0],
      amount: TRANSFER_AMOUNT,
      unit: 'token',
      destinationSeed: DESTINATION_SEED,
      prepare: async (scenario) => {
        // The toolkit reports UTXO token types under `token_type`, in the same hex
        // encoding the indexer reports as `tokenType`; if this probe ever skips a
        // provisioned environment, compare the two encodings first.
        const walletState = await scenario.toolkit.showPublicWalletState(
          scenario.wallet.source.address,
        );
        const holdings = CANDIDATE_TOKEN_TYPES.map((tokenType) => ({
          tokenType,
          spendable: walletState.utxos
            .filter((utxo) => utxo.token_type === tokenType)
            .reduce((total, utxo) => total + utxo.value, 0),
        }));
        log.debug(
          'Funding wallet holdings of the candidate token types: ' +
            holdings.map(({ tokenType, spendable }) => `${tokenType}=${spendable}`).join(', '),
        );

        // Strictly greater: the transfer has to leave change behind, so that it creates
        // a destination output and a source output just as the NIGHT transfer does.
        const usable = holdings.find((holding) => holding.spendable > TRANSFER_AMOUNT);
        if (usable === undefined) {
          return `environment not provisioned: the funding wallet cannot spend any of the ${holdings.length} custom unshielded token type(s) recorded for this environment, so ${TRANSFER_AMOUNT} cannot be transferred leaving change behind`;
        }

        // Assigned before the scenario submits the transfer, which happens once this
        // hook has returned.
        scenario.token.tokenType = usable.tokenType;
        return null;
      },
    });

    defineUnshieldedTransferTests(scenario);
  },
);
