// This file is part of midnightntwrk/midnight-indexer
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import '@utils/logging/test-logging-hooks';
import log from '@utils/logging/logger';
import { env } from 'environment/model';
import type { TestContext } from 'vitest';
import { randomBytes } from 'crypto';
import { IndexerWsClient } from '@utils/indexer/websocket-client';
import { ToolkitWrapper } from '@utils/toolkit/toolkit-wrapper';
import dataProvider from '@utils/testdata-provider';
import { retry } from '@utils/retry-helper';
import { getWalletLastActiveEpochMicros } from '@utils/undeployed/indexer-postgres';

// Server-side polling parameters under test (indexer-api/config.yaml:
// progress_update_interval 30s, keep_wallet_alive_interval 10m; polling.rs:
// JITTER_FRACTION 0.2, IDLE_BACKOFF_MAX_MULTIPLE 8; progress cache TTL 5s).
const BASE_INTERVAL_MS = 30_000;
const IDLE_BACKOFF_MAX_MULTIPLE = 8;
const PROGRESS_CACHE_TTL_MS = 5_000;

// Observed-gap bounds: the ±20% jitter window widened by scheduling and
// websocket delivery slack.
const FIRST_EMIT_MAX_MS = 5_000;
const BASE_GAP_MS = { min: 22_000, max: 40_000 }; // jittered 30s = [24s, 36s]
const DOUBLED_GAP_MS = { min: 45_000, max: 80_000 }; // jittered 60s = [48s, 72s]

// Worst case for the first progress update reporting a change, measured from
// transaction confirmation: the in-flight 4×base sleep completes just before
// the change becomes visible, the interval doubles to the 8×base cap, and the
// change is only reported one full capped gap later (plus cache staleness).
const RESET_DETECTION_BUDGET_MS =
  (4 + IDLE_BACKOFF_MAX_MULTIPLE) * BASE_INTERVAL_MS * 1.2 + PROGRESS_CACHE_TTL_MS + 10_000;

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

async function waitFor(predicate: () => boolean, timeoutMs: number, what: string): Promise<void> {
  const start = Date.now();
  while (!predicate()) {
    if (Date.now() - start > timeoutMs) {
      throw new Error(`Timed out after ${timeoutMs}ms waiting for ${what}`);
    }
    await sleep(250);
  }
}

interface ProgressSample {
  atMs: number;
  value: number;
}

// The asserted timing bounds are only trustworthy against a dedicated local
// stack, and the keep-alive check reads the stack's Postgres directly.
describe.skipIf(!env.isUndeployedEnv())('subscription polling', () => {
  let toolkit: ToolkitWrapper;

  beforeAll(async () => {
    toolkit = new ToolkitWrapper({});
    await toolkit.start();
  }, 120_000);

  afterAll(async () => {
    await toolkit.stop();
  }, 60_000);

  describe('an unshielded transactions subscription for a never-used address', () => {
    let wsClient: IndexerWsClient;
    let unsubscribe: (() => void) | undefined;
    let subscribedAtMs: number;
    let destinationAddress: string;
    // Progress samples in arrival order; value = highestTransactionId.
    const progressSamples: ProgressSample[] = [];

    beforeAll(async () => {
      wsClient = new IndexerWsClient();
      await wsClient.connectionInit();

      // A never-used address: its highest transaction ID only moves when this
      // test sends a transaction to it, so the idle timing below is immune to
      // traffic generated by other test files running in parallel.
      destinationAddress = (await toolkit.showAddress(randomBytes(32).toString('hex'))).unshielded;

      subscribedAtMs = Date.now();
      unsubscribe = wsClient.subscribeToUnshieldedTransactionEvents(
        {
          next: (event) => {
            const data = event.data?.unshieldedTransactions;
            if (data?.__typename === 'UnshieldedTransactionsProgress') {
              progressSamples.push({ atMs: Date.now(), value: data.highestTransactionId });
            }
          },
        },
        { address: destinationAddress },
      );
    }, 60_000);

    afterAll(async () => {
      unsubscribe?.();
      await wsClient.connectionClose();
    });

    /**
     * While nothing changes for the subscribed address the progress polling
     * backs off: the first update is emitted immediately, the next one a
     * jittered base interval (30s ±20%) later and the following one a jittered
     * doubled interval (60s ±20%) after that.
     *
     * @given a subscription to unshielded transaction events for a never-used address
     * @when the arrival times of the first three progress updates are recorded
     * @then the first update arrives within 5 seconds of subscribing
     * @and the gap to the second update is a jittered base interval (22-40s)
     * @and the gap to the third update is a jittered doubled interval (45-80s)
     * @and all three updates report highestTransactionId 0
     */
    test(
      'should emit progress immediately and back off while the address is idle',
      { timeout: 200_000 },
      async (ctx: TestContext) => {
        ctx.task!.meta.custom = { labels: ['Subscription', 'Polling', 'UnshieldedTokens'] };

        await waitFor(
          () => progressSamples.length >= 3,
          FIRST_EMIT_MAX_MS + BASE_GAP_MS.max + DOUBLED_GAP_MS.max,
          'three progress updates',
        );

        const [first, second, third] = progressSamples;
        const gapToSecond = second.atMs - first.atMs;
        const gapToThird = third.atMs - second.atMs;
        log.info(`Idle unshielded progress gaps: ${gapToSecond}ms, then ${gapToThird}ms`);

        expect(first.atMs - subscribedAtMs).toBeLessThanOrEqual(FIRST_EMIT_MAX_MS);
        expect(gapToSecond).toBeGreaterThanOrEqual(BASE_GAP_MS.min);
        expect(gapToSecond).toBeLessThanOrEqual(BASE_GAP_MS.max);
        expect(gapToThird).toBeGreaterThanOrEqual(DOUBLED_GAP_MS.min);
        expect(gapToThird).toBeLessThanOrEqual(DOUBLED_GAP_MS.max);
        expect(progressSamples.slice(0, 3).every((sample) => sample.value === 0)).toBe(true);
      },
    );

    /**
     * Once the subscribed address receives a transaction, the backed-off
     * polling snaps back: the change is reported and the following update is
     * again one jittered base interval away.
     *
     * The timeout covers toolkit transaction generation plus the worst-case
     * detection window of a fully backed-off poller (see
     * RESET_DETECTION_BUDGET_MS).
     *
     * @given the idle subscription has backed off beyond the base interval
     * @when an unshielded transaction is sent to the subscribed address
     * @then a progress update reporting a higher highestTransactionId arrives
     *       within the backed-off polling window
     * @and the gap after that update returns to a jittered base interval (22-40s)
     */
    test(
      'should reset the polling interval when the address receives a transaction',
      { timeout: 720_000 },
      async (ctx: TestContext) => {
        ctx.task!.meta.custom = { labels: ['Subscription', 'Polling', 'UnshieldedTokens'] };

        const baselineValue = progressSamples.at(-1)!.value;

        const transactionResult = await toolkit.generateSingleTx(
          dataProvider.getFundingSeed(),
          'unshielded',
          destinationAddress,
          1,
        );
        const confirmedAtMs = Date.now();
        log.info(`Unshielded transaction sent to subscribed address: ${transactionResult.txHash}`);

        await waitFor(
          () => progressSamples.some((sample) => sample.value > baselineValue),
          RESET_DETECTION_BUDGET_MS,
          'a progress update reporting the new transaction',
        );
        const changedIndex = progressSamples.findIndex((sample) => sample.value > baselineValue);
        const changed = progressSamples[changedIndex];
        log.info(`Change reported ${changed.atMs - confirmedAtMs}ms after confirmation`);

        // The poll that observed the change resets its interval to base, so
        // the next update must arrive one jittered base interval later.
        await waitFor(
          () => progressSamples.length > changedIndex + 1,
          BASE_GAP_MS.max + 5_000,
          'the progress update following the reset',
        );
        const gapAfterReset = progressSamples[changedIndex + 1].atMs - changed.atMs;
        log.info(`Gap after reset: ${gapAfterReset}ms`);

        expect(changed.value).toBeGreaterThan(baselineValue);
        expect(gapAfterReset).toBeGreaterThanOrEqual(BASE_GAP_MS.min);
        expect(gapAfterReset).toBeLessThanOrEqual(BASE_GAP_MS.max);
      },
    );
  });

  describe('the keep-alive heartbeat of a shielded transactions subscription', () => {
    let wsClient: IndexerWsClient;
    let unsubscribe: (() => void) | undefined;
    let sessionId: string | undefined;

    beforeAll(async () => {
      wsClient = new IndexerWsClient();
      await wsClient.connectionInit();
    }, 30_000);

    afterAll(async () => {
      unsubscribe?.();
      if (sessionId) {
        await wsClient.closeWalletSession(sessionId);
      }
      await wsClient.connectionClose();
    });

    /**
     * The wallet keep-alive heartbeat is throttled: it still fires once
     * immediately when the subscription starts, but no longer refreshes the
     * wallet's last-active timestamp every minute (the default interval is
     * now 10 minutes).
     *
     * @given a wallet session opened for a fresh viewing key
     * @when a shielded transactions subscription is held open while the
     *       wallet's last-active timestamp is sampled from the indexer database
     * @then the timestamp is refreshed once at subscription start
     * @and it is not refreshed again within the following 90 seconds
     */
    test(
      'should refresh wallet activity once at subscription start and then throttle',
      { timeout: 180_000 },
      async (ctx: TestContext) => {
        ctx.task!.meta.custom = { labels: ['Subscription', 'Polling', 'Wallet'] };

        const viewingKey = await toolkit.showViewingKey(randomBytes(32).toString('hex'));
        sessionId = await wsClient.openWalletSession(viewingKey);
        const connectedSessionId = sessionId;

        const lastActiveAtConnect = await retry(
          async () => {
            const value = await getWalletLastActiveEpochMicros(connectedSessionId);
            if (value === undefined) {
              throw new Error('wallet row not visible yet');
            }
            return value;
          },
          { maxRetries: 5, delayMs: 1000, retryLabel: 'read last_active after connect' },
        );

        // Ensure the heartbeat gets a strictly later timestamp than the
        // connect mutation's own last-active write.
        await sleep(2_000);

        unsubscribe = wsClient.subscribeToShieldedTransactionEvents({}, connectedSessionId);

        // The first keep-alive tick fires immediately on subscribing.
        const lastActiveAtSubscribe = await retry(
          async () => {
            const value = await getWalletLastActiveEpochMicros(connectedSessionId);
            if (value === undefined || value <= lastActiveAtConnect) {
              throw new Error('immediate keep-alive heartbeat not written yet');
            }
            return value;
          },
          { maxRetries: 15, delayMs: 1000, retryLabel: 'read last_active after subscribing' },
        );

        // The previous default heartbeat interval (1m) would rewrite the
        // timestamp within this window; the throttled one (10m jittered, so
        // 8m at the earliest) must not.
        await sleep(90_000);
        const lastActiveAfterIdle = await getWalletLastActiveEpochMicros(connectedSessionId);

        expect(lastActiveAtSubscribe).toBeGreaterThan(lastActiveAtConnect);
        expect(lastActiveAfterIdle).toBe(lastActiveAtSubscribe);
      },
    );

    // Deferred end-to-end proof that the throttled heartbeat keeps a wallet
    // active beyond the wallet-indexer's 30m inactivity TTL: it needs
    // interval/TTL environment pass-throughs in docker-compose.yaml to run in
    // reasonable time — tracked in midnightntwrk/midnight-indexer#1372.
    test.todo('should keep a subscribed wallet active beyond the wallet-indexer inactivity TTL');
  });

  describe('a shielded transactions subscription on an idle wallet', () => {
    let wsClient: IndexerWsClient;
    let unsubscribe: (() => void) | undefined;
    let sessionId: string | undefined;

    beforeAll(async () => {
      wsClient = new IndexerWsClient();
      await wsClient.connectionInit();
    }, 30_000);

    afterAll(async () => {
      unsubscribe?.();
      if (sessionId) {
        await wsClient.closeWalletSession(sessionId);
      }
      await wsClient.connectionClose();
    });

    /**
     * Idle backoff must not delay the initial sync signal: the first progress
     * update is still emitted immediately and updates keep flowing while the
     * wallet has no relevant transactions.
     *
     * Shielded change detection is global (any zswap activity on chain resets
     * the backoff), so only base-interval bounds are asserted: consecutive
     * updates are one jittered current-interval apart and that interval never
     * drops below the base.
     *
     * @given a wallet session opened for a fresh viewing key
     * @when a shielded transactions subscription is opened and left idle
     * @then the first progress update arrives within 5 seconds of subscribing
     * @and a further progress update arrives one jittered base interval later (22-40s)
     * @and the reported highestZswapEndIndex does not decrease between updates
     */
    test(
      'should emit progress immediately and keep emitting while idle',
      { timeout: 90_000 },
      async (ctx: TestContext) => {
        ctx.task!.meta.custom = { labels: ['Subscription', 'Polling', 'Wallet'] };

        const viewingKey = await toolkit.showViewingKey(randomBytes(32).toString('hex'));
        sessionId = await wsClient.openWalletSession(viewingKey);

        // Progress samples in arrival order; value = highestZswapEndIndex.
        const progressSamples: ProgressSample[] = [];
        const subscribedAtMs = Date.now();
        unsubscribe = wsClient.subscribeToShieldedTransactionEvents(
          {
            next: (payload) => {
              const event = payload.data?.shieldedTransactions;
              if (event?.__typename === 'ShieldedTransactionsProgress') {
                progressSamples.push({ atMs: Date.now(), value: event.highestZswapEndIndex });
              }
            },
          },
          sessionId,
        );

        await waitFor(
          () => progressSamples.length >= 2,
          FIRST_EMIT_MAX_MS + BASE_GAP_MS.max,
          'two shielded progress updates',
        );

        const [first, second] = progressSamples;
        const gap = second.atMs - first.atMs;
        log.info(`Idle shielded progress gap: ${gap}ms`);

        expect(first.atMs - subscribedAtMs).toBeLessThanOrEqual(FIRST_EMIT_MAX_MS);
        expect(gap).toBeGreaterThanOrEqual(BASE_GAP_MS.min);
        expect(gap).toBeLessThanOrEqual(BASE_GAP_MS.max);
        expect(second.value).toBeGreaterThanOrEqual(first.value);
      },
    );
  });
});
