#!/usr/bin/env python3
"""Generate wasm-deps/Cargo.toml — the no_std crate universe (crates_wasm) for
the WASM runtime, resolved separately from the std workspace so features don't
unify with std members.

Input is a `cargo metadata --filter-platform wasm32v1-none` of a throwaway
manifest that depends on midnight-node-runtime with default-features=false —
i.e. the EXACT no_std tree. We emit the first-party closure's external deps with
the features cargo resolved for wasm, all default-features=false.

  scripts/buck2/gen-wasm-deps.sh   # regenerates the resolve + this manifest
"""
import json, os, sys, tomllib, urllib.parse

WASM_META = sys.argv[1]
OUT = sys.argv[2]
ROOT = sys.argv[3]  # workspace root (for [patch])

m = json.load(open(WASM_META))
root_manifest = tomllib.load(open(os.path.join(ROOT, "Cargo.toml"), "rb"))
pkg = {p["id"]: p for p in m["packages"]}
rfeat = {n["id"]: set(n.get("features") or []) for n in m["resolve"]["nodes"]}
present = set(pkg)  # only packages cargo kept for wasm

# first-party = path packages (except the throwaway resolver)
fp_closure = {i for i, p in pkg.items()
              if not p.get("source") and p["name"] != "wasm-resolve"}

entries = {}  # key -> entry (union features across first-party consumers)
for mid in fp_closure:
    p = pkg[mid]
    for dep in p["dependencies"]:
        if dep.get("kind") in ("dev", "build") or not dep.get("source"):
            continue
        # keep only deps whose resolved package survived the wasm filter
        cand = [q for q in m["packages"]
                if q["name"] == dep["name"] and q.get("source")]
        if not cand:
            continue
        key = dep.get("rename") or dep["name"]
        e = entries.setdefault(key, {"name": dep["name"], "key": key,
                                     "source": dep["source"], "req": dep["req"],
                                     "features": set()})
        # union the resolved no_std features of the matching package(s)
        for q in cand:
            e["features"].update(rfeat.get(q["id"], set()))

def ts(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def fmt(e):
    parts = []
    if e["key"] != e["name"]:
        parts.append(f"package = {ts(e['name'])}")
    src = e["source"]
    if src.startswith("git+"):
        u = urllib.parse.urlparse(src[4:])
        q = urllib.parse.parse_qs(u.query)
        parts.append(f"git = {ts(u._replace(query='', fragment='').geturl())}")
        for k in ("tag", "branch", "rev"):
            if k in q:
                parts.append(f"{k} = {ts(q[k][0])}")
    else:
        parts.append(f"version = {ts(e['req'])}")
    # Natural feature set (minus "default", which we disable). reindeer's
    # execution-platform config handles the host/target std split — don't strip
    # std here or the host proc-macro builds that legitimately need it break.
    feats = sorted(f for f in e["features"] if f != "default")
    if feats:
        parts.append("features = [" + ", ".join(ts(f) for f in feats) + "]")
    parts.append("default-features = false")
    return "{ " + ", ".join(parts) + " }"

with open(OUT, "w") as f:
    f.write("""# @generated by scripts/buck2/gen-wasm-deps.sh — the no_std crate universe
# (crates_wasm) for the WASM runtime. Standalone [workspace] so Cargo resolves
# features independently from the std members. Regenerate via the .sh wrapper.
[package]
name = "wasm-deps-resolver"
version = "0.0.0"
edition = "2024"
publish = false

# resolver = "2" decouples host (build-script + proc-macro) feature unification
# from normal deps. Without it a workspace defaults to resolver "1" (regardless
# of edition), which unifies e.g. `either/std` pulled by a host proc-macro chain
# (aquamarine -> itertools -> either/std) into the wasm/target build of `either`,
# dragging `std` onto wasm32. Resolver 2 keeps the target build no_std.
[workspace]
resolver = "2"

[lib]
path = "src/lib.rs"

[dependencies]
""")
    for k in sorted(entries):
        f.write(f"{k} = {fmt(entries[k])}\n")
    # Merge the workspace [patch] (git/version redirects) with
    # third-party/patches.toml (buck-specific overlay, notably the patched
    # `proc-macro-crate` whose `crate_name()` resolves renamed deps like
    # `codec = { package = "parity-scale-codec" }` under buck's sandbox — the
    # unpatched one errors "Could not find parity-scale-codec"). patches.toml
    # `path`s are relative to third-party/; reindeer refuses path deps that
    # escape the third-party-dir (`../third-party/…`), so we expose them via a
    # `wasm-deps/patched -> ../third-party/patched` symlink and reference the
    # path verbatim. Local overlay wins on key collisions.
    patches = {reg: dict(crates) for reg, crates in root_manifest.get("patch", {}).items()}
    tp_patches_path = os.path.join(ROOT, "third-party", "patches.toml")
    if os.path.exists(tp_patches_path):
        for reg, crates in tomllib.load(open(tp_patches_path, "rb")).items():
            patches.setdefault(reg, {}).update({n: dict(s) for n, s in crates.items()})
        link = os.path.join(os.path.dirname(OUT), "patched")
        if not os.path.islink(link) and not os.path.exists(link):
            os.symlink(os.path.join("..", "third-party", "patched"), link)
    for reg in sorted(patches):
        f.write(f"\n[patch.{ts(reg)}]\n")
        for name, spec in sorted(patches[reg].items()):
            parts = [f"{kk} = {ts(vv)}" for kk, vv in spec.items()]
            f.write(f"{name} = {{ {', '.join(parts)} }}\n")

os.makedirs(os.path.join(os.path.dirname(OUT), "src"), exist_ok=True)
libp = os.path.join(os.path.dirname(OUT), "src", "lib.rs")
if not os.path.exists(libp):
    open(libp, "w").write("// Empty — resolves the no_std WASM dep tree.\n")

# Sidecar for gen-first-party.py: per first-party closure crate, its no_std
# feature set AND its actual wasm dependency crate names (from the wasm-filtered
# resolve — so a std-only dep like ledger's `lazy_static`, absent here, is
# dropped on wasm32 rather than kept just because a wasm-deps target happens to
# exist for it). gen-first-party emits a `select()` on `cpu:wasm32` from this.
nodes = {n["id"]: n for n in m["resolve"]["nodes"]}
sidecar = {}
for mid in fp_closure:
    node = nodes.get(mid, {})
    dep_names = set()
    for rd in node.get("deps", []):
        # normal (kind null) deps only, matching gen-first-party's link deps;
        # build/dev-only edges are not link deps under buck.
        if all(k.get("kind") is not None for k in (rd.get("dep_kinds") or [{}])):
            continue
        dep_names.add(pkg[rd["pkg"]]["name"])
    sidecar[pkg[mid]["name"]] = {
        "features": sorted(f for f in rfeat.get(mid, set()) if f != "default"),
        "deps": sorted(dep_names),
    }
sc_path = os.path.join(os.path.dirname(OUT), "first-party-wasm.json")
with open(sc_path, "w") as f:
    json.dump(sidecar, f, indent=1, sort_keys=True)

print(f"wrote {OUT}: {len(entries)} external wasm deps from "
      f"{len(fp_closure)} first-party crates; sidecar {sc_path} "
      f"({len(sidecar)} crates)")
