// This file is part of midnight-node.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import fs from "fs";
import path from "path";
import YAML from "yaml";

import { discoverValidators } from "./discoverValidators";

const SAFE_NAMESPACE = /^[A-Za-z0-9_][A-Za-z0-9_-]*$/;

export interface ForkManifestOptions {
  namespace: string;
  composeFile: string;
  env: Record<string, string>;
}

/**
 * Write the consumer-facing connection manifest for a running fork.
 *
 * The manifest is the stable contract external compose overlays rely on to
 * attach to a fork (docker network name + node endpoints) without knowing
 * anything about this repo's layout. Keys are load-bearing for downstream
 * repos — treat renames/removals as breaking changes.
 */
export function writeForkManifest(options: ForkManifestOptions): string {
  const { namespace, composeFile, env } = options;

  const validators = discoverValidators(composeFile);
  const networkName = resolveComposeNetworkName(composeFile);
  const nodeImage = env.NODE_IMAGE ?? "";
  const nodeTag = extractImageTag(nodeImage);

  const primary = validators[0];
  const lines = [
    `# Generated by \`midnight-up run ${namespace}\`; reflects the most recent bring-up.`,
    `# Connection contract for external consumers: join the docker network below`,
    `# (declare it \`external: true\`) and source this file, e.g.`,
    `#   docker compose --env-file <this file> -f your-overlay.yaml up -d`,
    `# MIDNIGHT_FORK_NETWORK_ID defaults to the fork namespace; override it if your`,
    `# consumer needs a different network-id spelling.`,
    `MIDNIGHT_FORK_NAMESPACE=${namespace}`,
    `MIDNIGHT_FORK_NETWORK=${networkName}`,
    `MIDNIGHT_FORK_NETWORK_ID=${namespace}`,
    `MIDNIGHT_FORK_NODE_IMAGE=${nodeImage}`,
    `MIDNIGHT_FORK_NODE_TAG=${nodeTag}`,
    // Fork endpoints are intentionally unencrypted: one is confined to the
    // private Docker network and the other is published on localhost only.
    `MIDNIGHT_FORK_NODE_WS=ws://${primary.name}:${primary.rpcPort}`, // nosemgrep: javascript.lang.security.detect-insecure-websocket.detect-insecure-websocket
    `MIDNIGHT_FORK_NODE_WS_HOST=ws://localhost:${primary.hostRpcPort}`, // nosemgrep: javascript.lang.security.detect-insecure-websocket.detect-insecure-websocket
    `MIDNIGHT_FORK_VALIDATORS=${validators.map((v) => v.name).join(",")}`,
  ];
  for (const v of validators) {
    lines.push(
      `MIDNIGHT_FORK_${envKey(v.name)}_WS=ws://${v.name}:${v.rpcPort}`, // nosemgrep: javascript.lang.security.detect-insecure-websocket.detect-insecure-websocket
    );
    lines.push(
      `MIDNIGHT_FORK_${envKey(v.name)}_WS_HOST=ws://localhost:${v.hostRpcPort}`, // nosemgrep: javascript.lang.security.detect-insecure-websocket.detect-insecure-websocket
    );
  }

  const manifestPath = forkManifestPath(namespace);
  fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
  fs.writeFileSync(manifestPath, lines.join("\n") + "\n");
  return manifestPath;
}

export function forkManifestPath(namespace: string): string {
  if (!SAFE_NAMESPACE.test(namespace)) {
    throw new Error(
      `Invalid fork namespace '${namespace}': expected only letters, digits, underscores, and hyphens`,
    );
  }

  // The validation above constrains namespace to one filename-safe component.
  // prettier-ignore
  return path.resolve(__dirname, "../../artifacts", `${namespace}.manifest.env`); // nosemgrep: javascript.lang.security.audit.path-traversal.path-join-resolve-traversal.path-join-resolve-traversal
}

/** Extract a tag from the final path segment of an OCI/Docker image reference. */
function extractImageTag(image: string): string {
  const withoutDigest = image.split("@", 1)[0];
  const finalSlash = withoutDigest.lastIndexOf("/");
  const tagSeparator = withoutDigest.lastIndexOf(":");
  return tagSeparator > finalSlash ? withoutDigest.slice(tagSeparator + 1) : "";
}

function resolveComposeNetworkName(composeFile: string): string {
  const parsed = YAML.parse(fs.readFileSync(composeFile, "utf-8")) as {
    networks?: Record<string, { name?: string } | null>;
  };
  const explicit = parsed?.networks?.default?.name;
  if (explicit) return explicit;
  // Without an explicit name, compose derives `<project>_default` and the
  // default project name is the compose file's directory name.
  return `${path.basename(path.dirname(composeFile))}_default`;
}

function envKey(serviceName: string): string {
  return serviceName.toUpperCase().replace(/[^A-Z0-9]/g, "_");
}
