// This file is part of midnight-node.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import fs from "fs";
import path from "path";
import YAML from "yaml";

export const GENESIS_CONFIG_DIRNAME = "genesis-config";

/** Deterministic path of the override yaml generated by generateGenesisComposeOverride. */
export function genesisOverridePath(
  composeDir: string,
  network: string,
): string {
  return path.join(
    path.resolve(composeDir),
    `${network}.genesis.override.yaml`,
  );
}

export interface GenesisOverrideOptions {
  /** Base compose file of the well-known network. */
  composeFile: string;
  /** Network name (devnet, qanet, ...) — drives the override filename. */
  network: string;
  /** Resolved environment (process env + --env-file overrides). */
  env: Record<string, string>;
}

export interface GenesisOverrideResult {
  overridePath: string;
  /** Services whose seed env var was set and got seed files wired in. */
  seededServices: string[];
  /** service -> unset env var name, for services that could not be seeded. */
  missingSeedVars: Record<string, string>;
}

/**
 * Per-key-type seed file names and the env var suffix that overrides each.
 * For a base var `MIDNIGHT_NODE_01_0_SEED`, the per-type vars are
 * `MIDNIGHT_NODE_01_0_AURA_SEED`, `..._GRANDPA_SEED`, `..._CROSS_CHAIN_SEED`.
 */
const SEED_FILE_TYPES = [
  { file: "aura.seed", envSuffix: "AURA" },
  { file: "grandpa.seed", envSuffix: "GRANDPA" },
  { file: "cross_chain.seed", envSuffix: "CROSS_CHAIN" },
] as const;

/**
 * Generates the docker-compose override that wires validator keys into a
 * from-genesis bring-up.
 *
 * The base compose files pass each validator's seed phrase as a `SEED_PHRASE`
 * env var, but the node only imports keystore keys from AURA_SEED_FILE /
 * GRANDPA_SEED_FILE / CROSS_CHAIN_SEED_FILE (see node/src/command.rs), so a
 * bare bring-up would start every validator with an empty keystore. For each
 * service whose SEED_PHRASE references a set env var, this writes the phrase
 * to a per-service seed file and points all three *_SEED_FILE vars at it —
 * the node derives the sr25519/ed25519/ecdsa keypairs from the same phrase,
 * matching how the pre-fork tooling populated keystores from the single
 * MIDNIGHT_NODE_*_SEED secret.
 *
 * Networks whose validators were deployed with a distinct phrase per key type
 * can set per-type vars instead (the base var's `_SEED` suffix is replaced by
 * `_AURA_SEED` / `_GRANDPA_SEED` / `_CROSS_CHAIN_SEED`); each key type falls
 * back to the base var when its per-type var is unset. A service is seeded
 * only when all three key types resolve to a phrase.
 */
export function generateGenesisComposeOverride(
  opts: GenesisOverrideOptions,
): GenesisOverrideResult {
  const { composeFile, network, env } = opts;
  const composeDir = path.dirname(path.resolve(composeFile));

  const compose = YAML.parse(fs.readFileSync(composeFile, "utf8"));
  const services: Record<string, { environment?: Record<string, unknown> }> =
    compose?.services ?? {};

  const seedsRoot = path.join(composeDir, GENESIS_CONFIG_DIRNAME, "seeds");
  const overrideServices: Record<string, unknown> = {};
  const seededServices: string[] = [];
  const missingSeedVars: Record<string, string> = {};

  for (const [name, service] of Object.entries(services)) {
    const seedRef = service?.environment?.SEED_PHRASE;
    if (typeof seedRef !== "string") {
      continue;
    }
    const varMatch = seedRef.match(/^\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?$/);
    if (!varMatch) {
      console.warn(
        `⚠️  ${name}: SEED_PHRASE is not a plain env var reference (${seedRef}); skipping seed wiring for it.`,
      );
      continue;
    }
    const varName = varMatch[1];
    const basePhrase = env[varName]?.trim();
    const varPrefix = varName.replace(/_SEED$/, "");
    const phrases: Record<string, string> = {};
    const unresolvedVars: string[] = [];
    for (const { file, envSuffix } of SEED_FILE_TYPES) {
      const typeVar = `${varPrefix}_${envSuffix}_SEED`;
      const phrase = env[typeVar]?.trim() || basePhrase;
      if (phrase) {
        phrases[file] = phrase;
      } else {
        unresolvedVars.push(typeVar);
      }
    }
    if (unresolvedVars.length === SEED_FILE_TYPES.length) {
      missingSeedVars[name] = varName;
      continue;
    }
    if (unresolvedVars.length > 0) {
      console.warn(
        `⚠️  ${name}: per-key-type seeds are incomplete (${unresolvedVars.join(", ")} unset, no ${varName} fallback); skipping seed wiring for it.`,
      );
      missingSeedVars[name] = varName;
      continue;
    }

    const serviceSeedDir = path.join(seedsRoot, name);
    fs.mkdirSync(serviceSeedDir, { recursive: true, mode: 0o700 });
    for (const { file } of SEED_FILE_TYPES) {
      fs.writeFileSync(path.join(serviceSeedDir, file), phrases[file], {
        mode: 0o600,
      });
    }

    overrideServices[name] = {
      environment: {
        AURA_SEED_FILE: "/seeds/aura.seed",
        GRANDPA_SEED_FILE: "/seeds/grandpa.seed",
        CROSS_CHAIN_SEED_FILE: "/seeds/cross_chain.seed",
        // The node does not consume SEED_PHRASE; blank it so nothing appears
        // to depend on it and the raw phrase stays out of container env.
        SEED_PHRASE: "",
      },
      volumes: [`./${GENESIS_CONFIG_DIRNAME}/seeds/${name}:/seeds:ro`],
    };
    seededServices.push(name);
  }

  const overridePath = genesisOverridePath(composeDir, network);
  fs.writeFileSync(
    overridePath,
    YAML.stringify({ services: overrideServices }),
  );
  return { overridePath, seededServices, missingSeedVars };
}
