//! Offline session-key generation from a runtime wasm blob.
//!
//! Executes the `SessionKeys_generate_session_keys` and `SessionKeys_decode_session_keys`
//! runtime APIs directly on a provided wasm code blob (optionally compressed, e.g.
//! `*.compact.compressed.wasm`), with the node's on-disk keystore exposed through host
//! functions. This allows generating and registering session keys for a runtime that is
//! not active on chain yet — the published wasm of a future runtime upgrade acts as the
//! source of truth for the expected key set, and the generated seeds are persisted in the
//! node keystore exactly as `author_rotateKeys` would do.
//!
//! The execution pattern mirrors `sc_chain_spec::GenesisConfigBuilderRuntimeCaller`.

use anyhow::{Context, anyhow};
use parity_scale_codec::{Decode, Encode};
use sc_executor::WasmExecutor;
use sp_core::crypto::KeyTypeId;
use sp_core::traits::{CallContext, CodeExecutor, RuntimeCode, WrappedRuntimeCode};
use sp_keystore::KeystoreExt;
use sp_state_machine::BasicExternalities;
use std::sync::Arc;

/// Session keys generated by executing a runtime wasm blob offline.
#[derive(Debug, Eq, PartialEq)]
pub struct WasmSessionKeys {
	/// blake2-256 hash of the wasm file content, to be verified against the announced
	/// runtime upgrade (e.g. the hash used with `authorize_upgrade`).
	pub code_hash: [u8; 32],
	/// SCALE-encoded opaque session keys blob, as returned by `generate_session_keys`.
	pub opaque: Vec<u8>,
	/// (key type id, public key bytes) pairs decoded by the runtime itself.
	pub keys: Vec<(KeyTypeId, Vec<u8>)>,
}

/// Return type of the `SessionKeys_generate_session_keys` runtime API (version 2).
#[derive(Decode)]
struct OpaqueGeneratedSessionKeys {
	keys: Vec<u8>,
	_proof: Vec<u8>,
}

/// Generates fresh session keys by executing `SessionKeys_generate_session_keys` of the
/// runtime wasm at `wasm_path`, persisting the generated seeds into the node keystore at
/// `keystore_path`, and decodes the resulting opaque blob with the same runtime.
pub fn generate_session_keys_from_wasm(
	wasm_path: &str,
	keystore_path: &str,
) -> anyhow::Result<WasmSessionKeys> {
	let code = std::fs::read(wasm_path)
		.with_context(|| format!("Failed to read runtime wasm file {wasm_path}"))?;
	let code_hash = sp_crypto_hashing::blake2_256(&code);
	let keystore = sc_keystore::LocalKeystore::open(keystore_path, None)
		.with_context(|| format!("Failed to open keystore at {keystore_path}"))?;

	// Only the standard substrate host functions are provided. Chain-specific host
	// functions the runtime may import are linked as missing: session-key generation
	// never calls them, so this stays runtime-agnostic.
	let executor = WasmExecutor::<sp_io::SubstrateHostFunctions>::builder()
		.with_allow_missing_host_functions(true)
		.build();
	let code_fetcher = WrappedRuntimeCode(code.as_slice().into());
	let runtime_code =
		RuntimeCode { heap_pages: None, code_fetcher: &code_fetcher, hash: code_hash.to_vec() };
	let mut ext = BasicExternalities::new_empty();
	ext.register_extension(KeystoreExt(Arc::new(keystore)));

	let generated = executor
		.call(
			&mut ext,
			&runtime_code,
			"SessionKeys_generate_session_keys",
			// (owner, seed) arguments of the version 2 API
			&(Vec::<u8>::new(), Option::<Vec<u8>>::None).encode(),
			CallContext::Offchain,
		)
		.0
		.map_err(|e| anyhow!("'SessionKeys_generate_session_keys' wasm call failed: {e}"))?;
	let generated = OpaqueGeneratedSessionKeys::decode(&mut &generated[..]).map_err(|e| {
		anyhow!(
			"Failed to decode generated session keys \
				 (the runtime may implement an unsupported SessionKeys API version): {e}"
		)
	})?;

	let decoded = executor
		.call(
			&mut ext,
			&runtime_code,
			"SessionKeys_decode_session_keys",
			&generated.keys.encode(),
			CallContext::Offchain,
		)
		.0
		.map_err(|e| anyhow!("'SessionKeys_decode_session_keys' wasm call failed: {e}"))?;
	let decoded = <Option<Vec<(Vec<u8>, KeyTypeId)>>>::decode(&mut &decoded[..])
		.map_err(|e| anyhow!("Failed to decode session keys returned by the runtime: {e}"))?
		.ok_or_else(|| {
			anyhow!("the provided runtime could not decode the generated session keys")
		})?;

	Ok(WasmSessionKeys {
		code_hash,
		opaque: generated.keys,
		keys: decoded.into_iter().map(|(bytes, id)| (id, bytes)).collect(),
	})
}
