// This file is part of midnight-node.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_federated_authority`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-09-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-10-0-48-195.eu-west-1.compute.internal`, CPU: `Intel(R) Xeon(R) Platinum 8488C`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./midnight-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// *
// --extrinsic
// *
// --exclude-extrinsics
// pallet_safe_mode::force_release_deposit,pallet_safe_mode::force_slash_deposit
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./runtime/src/weights
// --header
// ./LICENSE_HEADER.txt
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_federated_authority`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_federated_authority::weights::WeightInfo for WeightInfo<T> {
	/// Storage: `FederatedAuthority::Motions` (r:1 w:1)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 2]`.
	fn motion_approve(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177 + a * (5 ±0)`
		//  Estimated: `3642 + a * (5 ±0)`
		// Minimum execution time: 14_924_000 picoseconds.
		Weight::from_parts(16_753_927, 0)
			.saturating_add(Weight::from_parts(0, 3642))
			// Standard Error: 15_836
			.saturating_add(Weight::from_parts(252_369, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 5).saturating_mul(a.into()))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:1)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_approve_new() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `3579`
		// Minimum execution time: 12_379_000 picoseconds.
		Weight::from_parts(14_127_000, 0)
			.saturating_add(Weight::from_parts(0, 3579))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:0)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_approve_ended() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3652`
		// Minimum execution time: 10_673_000 picoseconds.
		Weight::from_parts(12_072_000, 0)
			.saturating_add(Weight::from_parts(0, 3652))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:0)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 2]`.
	fn motion_approve_already_approved(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183 + a * (4 ±0)`
		//  Estimated: `3648 + a * (4 ±0)`
		// Minimum execution time: 10_830_000 picoseconds.
		Weight::from_parts(12_166_084, 0)
			.saturating_add(Weight::from_parts(0, 3648))
			// Standard Error: 9_085
			.saturating_add(Weight::from_parts(25_202, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(Weight::from_parts(0, 4).saturating_mul(a.into()))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:0)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_approve_exceeds_bounds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3656`
		// Minimum execution time: 10_709_000 picoseconds.
		Weight::from_parts(12_027_000, 0)
			.saturating_add(Weight::from_parts(0, 3656))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:1)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 2]`.
	fn motion_revoke(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183 + a * (4 ±0)`
		//  Estimated: `3648 + a * (4 ±0)`
		// Minimum execution time: 14_609_000 picoseconds.
		Weight::from_parts(25_008_372, 0)
			.saturating_add(Weight::from_parts(0, 3648))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 4).saturating_mul(a.into()))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:0)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_revoke_ended() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3656`
		// Minimum execution time: 10_010_000 picoseconds.
		Weight::from_parts(11_281_000, 0)
			.saturating_add(Weight::from_parts(0, 3656))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:0)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_revoke_not_found() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `3579`
		// Minimum execution time: 6_643_000 picoseconds.
		Weight::from_parts(7_666_000, 0)
			.saturating_add(Weight::from_parts(0, 3579))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:0)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 2]`.
	fn motion_revoke_approval_missing(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183 + a * (4 ±0)`
		//  Estimated: `3648 + a * (4 ±0)`
		// Minimum execution time: 9_929_000 picoseconds.
		Weight::from_parts(11_215_992, 0)
			.saturating_add(Weight::from_parts(0, 3648))
			// Standard Error: 8_719
			.saturating_add(Weight::from_parts(960, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(Weight::from_parts(0, 4).saturating_mul(a.into()))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:1)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_revoke_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3652`
		// Minimum execution time: 17_868_000 picoseconds.
		Weight::from_parts(20_359_000, 0)
			.saturating_add(Weight::from_parts(0, 3652))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:0)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_close_still_ongoing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3652`
		// Minimum execution time: 10_073_000 picoseconds.
		Weight::from_parts(11_335_000, 0)
			.saturating_add(Weight::from_parts(0, 3652))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:1)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_close_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3652`
		// Minimum execution time: 17_572_000 picoseconds.
		Weight::from_parts(20_034_000, 0)
			.saturating_add(Weight::from_parts(0, 3652))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:1)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_close_approved() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `3656`
		// Minimum execution time: 20_984_000 picoseconds.
		Weight::from_parts(23_500_000, 0)
			.saturating_add(Weight::from_parts(0, 3656))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FederatedAuthority::Motions` (r:1 w:0)
	/// Proof: `FederatedAuthority::Motions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn motion_close_not_found() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `3579`
		// Minimum execution time: 6_771_000 picoseconds.
		Weight::from_parts(7_852_000, 0)
			.saturating_add(Weight::from_parts(0, 3579))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}
