// This file is part of midnight-node.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_cnight_observation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-09-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-10-0-48-195.eu-west-1.compute.internal`, CPU: `Intel(R) Xeon(R) Platinum 8488C`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./midnight-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// *
// --extrinsic
// *
// --exclude-extrinsics
// pallet_safe_mode::force_release_deposit,pallet_safe_mode::force_slash_deposit
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./runtime/src/weights
// --header
// ./LICENSE_HEADER.txt
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_cnight_observation`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_cnight_observation::weights::WeightInfo for WeightInfo<T> {
	/// Storage: `CNightObservation::CardanoTxCapacityPerBlock` (r:1 w:0)
	/// Proof: `CNightObservation::CardanoTxCapacityPerBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CNightObservation::InherentExecutedThisBlock` (r:1 w:1)
	/// Proof: `CNightObservation::InherentExecutedThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0xbbf4abef611bc3c9ca8cee3af9d8f7d14e7b9012096b41c4eb3aaf947f6ea429` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0xbbf4abef611bc3c9ca8cee3af9d8f7d14e7b9012096b41c4eb3aaf947f6ea429` (r:1 w:0)
	/// Storage: `CNightObservation::NextCardanoPosition` (r:1 w:1)
	/// Proof: `CNightObservation::NextCardanoPosition` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CNightObservation::CardanoBlockWindowSize` (r:1 w:0)
	/// Proof: `CNightObservation::CardanoBlockWindowSize` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CNightObservation::Mapping` (r:25600 w:12800)
	/// Proof: `CNightObservation::Mapping` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 12800]`.
	fn process_tokens(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `3689 + n * (4950 ±0)`
		// Minimum execution time: 14_264_000 picoseconds.
		Weight::from_parts(14_740_000, 0)
			.saturating_add(Weight::from_parts(0, 3689))
			// Standard Error: 9_959
			.saturating_add(Weight::from_parts(21_319_504, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 4950).saturating_mul(n.into()))
	}
	/// Storage: `CNightObservation::MainChainMappingValidatorAddress` (r:0 w:1)
	/// Proof: `CNightObservation::MainChainMappingValidatorAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_mapping_validator_contract_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_160_000 picoseconds.
		Weight::from_parts(3_847_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `CNightObservation::CNightIdentifier` (r:0 w:1)
	/// Proof: `CNightObservation::CNightIdentifier` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_cnight_identifier() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_218_000 picoseconds.
		Weight::from_parts(3_896_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `CNightObservation::MainChainAuthTokenAssetName` (r:0 w:1)
	/// Proof: `CNightObservation::MainChainAuthTokenAssetName` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_auth_token_asset_name() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_963_000 picoseconds.
		Weight::from_parts(3_604_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
