version: 2

updates:
  - package-ecosystem: "cargo"
    labels:
      - "bot:dependencies"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "fake"

  - package-ecosystem: "github-actions"
    labels:
      - "bot:github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    labels:
      - "bot:dependencies"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      all:
        patterns:
          - "*"
