[package]
name = "docs"
version = "0.1.0"
edition = "2024"
license-file.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
