chain = "res/testnet-02/chain-spec-raw.json"
base_path = "node/chain"

chainspec_name = "testnet-02-1"
chainspec_id = "testnet-02"
chainspec_network_id = "testnet"
chainspec_genesis_state = "res/genesis/genesis_state_testnet-02.mn"
chainspec_genesis_tx = "res/genesis/genesis_tx_testnet-02.mn"
chainspec_chain_type = "live"
chainspec_pc_chain_config = "res/testnet-02/pc-chain-config.json"
