[package]
name = "governance-helpers"
version = "0.1.0"
edition = "2024"
license-file.workspace = true

[dependencies]
subxt.workspace = true
subxt-signer.workspace = true
sp-crypto-hashing.workspace = true
scale-info.workspace = true
hex.workspace = true
log.workspace = true
thiserror.workspace = true

[lints]
workspace = true
