
//! Autogenerated weights for `pallet_system_parameters`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-12-18, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/midnight-node
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/midnight-node-runtime/midnight_node_runtime.wasm
// --genesis-builder=spec
// --wasm-execution=compiled
// --pallet=pallet_system_parameters
// --extrinsic=*
// --steps
// 2
// --repeat
// 1
// --output
// pallets/system-parameters/src/weights.rs
// --template=./res/weights-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_system_parameters`.
pub trait WeightInfo {
	fn update_terms_and_conditions() -> Weight;
	fn update_d_parameter() -> Weight;
}

/// Weights for `pallet_system_parameters` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SystemParameters::TermsAndConditionsStorage` (r:0 w:1)
	/// Proof: `SystemParameters::TermsAndConditionsStorage` (`max_values`: Some(1), `max_size`: Some(290), added: 785, mode: `MaxEncodedLen`)
	fn update_terms_and_conditions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SystemParameters::DParameterStorage` (r:0 w:1)
	/// Proof: `SystemParameters::DParameterStorage` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_d_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `SystemParameters::TermsAndConditionsStorage` (r:0 w:1)
	/// Proof: `SystemParameters::TermsAndConditionsStorage` (`max_values`: Some(1), `max_size`: Some(290), added: 785, mode: `MaxEncodedLen`)
	fn update_terms_and_conditions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
	/// Storage: `SystemParameters::DParameterStorage` (r:0 w:1)
	/// Proof: `SystemParameters::DParameterStorage` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_d_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
}
