// This file is part of midnightntwrk/midnight-indexer
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import fs from 'fs';
import { parse } from 'jsonc-parser';
import { env } from '../environment/model';

type JsonValue = string | number | boolean | null | JsonObject | JsonArray;
type JsonObject = { [key: string]: JsonValue };
type JsonArray = JsonValue[];

export interface ContractActionInfo {
  'action-type': string;
  'block-height': number;
  'block-hash': string;
}

export interface ContractInfo {
  'contract-address': string;
  'contract-actions': ContractActionInfo[];
}

/**
 * A contract known to have emitted public contract events (MIP-0002) on the
 * current environment's chain. Used by the contract-event integration tests to
 * assert real emitted-event payloads. Sourced from
 * `data/static/<env>/contract-events.jsonc`; absent until a test-data path that
 * deploys and calls an emit-bearing contract is wired for the environment, so
 * the data-dependent assertions skip until then.
 */
export interface EventEmittingContractInfo {
  /** Hex-encoded contract address that emitted at least one contract event. */
  'contract-address': string;
  /** Optional contract-event type names expected among the emitted events. */
  'event-types'?: string[];
}

/**
 * A contract known to hold a non-zero unshielded token balance on the current
 * environment's chain. Used by the unshieldedBalances regression tests (#1245):
 * the field silently returned an empty array for every contract from 3.0.0 to
 * 4.3.3, which format-only assertions could not catch.
 */
export interface TokenHoldingContractInfo {
  /** Hex-encoded contract address. */
  'contract-address': string;
  /** Hex-encoded unshielded token type expected among the contract's balances. */
  'token-type'?: string;
}

/**
 * A custom (non-NIGHT) unshielded token type the current environment's chain was
 * seen holding unspent, as generated by the block-scanner into
 * `data/static/<env>/unshielded-token-types.jsonc`. Only the token type is read
 * here; the per-owner holdings the fixture also records are there to make the
 * candidate reviewable by a human.
 */
interface CustomUnshieldedToken {
  /** Hex-encoded unshielded token type. */
  'token-type': string;
}

/**
 * Snapshot of a Cardano stake credential whose wallet has multiple backing
 * cNIGHT UTXOs. Used by the `dustGenerationStatus` aggregation test (#926):
 * the test asserts the indexer's reported `nightBalance` matches
 * `expectedTotalRaw`, and uses `individualAmountsRaw` for drift detection
 * (pre-fix the indexer reports a single UTXO's amount, which should match
 * one of the recorded individual amounts).
 */
export interface MultiUtxoCandidate {
  /** Cardano payment address currently holding the backing cNIGHT UTXOs. */
  cardanoAddress: string;
  /** CIP-19 stake address registered for DUST generation. */
  cardanoStakeKey: string;
  /** Number of backing cNIGHT UTXOs at the snapshot date. */
  expectedUtxoCount: number;
  /** Sum of raw cNIGHT amounts across all backing UTXOs at the snapshot date. */
  expectedTotalRaw: number;
  /** Raw cNIGHT amount of each backing UTXO at the snapshot date. */
  individualAmountsRaw: number[];
}

/**
 * Imports and parses JSONC data from a file.
 * @param filePath - The path to the JSONC file.
 * @returns The parsed JSON data.
 */
function importJsoncData(filePath: string): JsonValue {
  const fileContent = fs.readFileSync(filePath, 'utf-8');
  return parse(fileContent);
}

/**
 * Provides test data for various test scenarios across different environments.
 * The data is loaded from environment-specific JSON files during initialization.
 */
class TestDataProvider {
  private cardanoRewardAddresses: Record<string, string>;
  private unshieldedAddresses: Record<string, string>;
  private customUnshieldedTokenTypes: string[] | null;
  private multiUtxoCandidates: MultiUtxoCandidate[] | null;

  constructor() {
    this.cardanoRewardAddresses = {};
    this.unshieldedAddresses = {};
    this.customUnshieldedTokenTypes = null;
    this.multiUtxoCandidates = null;
  }

  /**
   * Gets the funding seed for the current environment.
   * First checks for an environment-specific variable (e.g., FUNDING_SEED_PREVIEW),
   * then falls back to a default seed for undeployed environments.
   * @returns The funding seed as a string.
   */
  getFundingSeed() {
    // Build the environment-specific variable name (e.g., FUNDING_SEED_PREVIEW)
    let envName = env.getCurrentEnvironmentName();
    let envNameUppercase = envName.toUpperCase().replace(/-/g, '_').replace('.', '_');

    const envVarName = `FUNDING_SEED_${envNameUppercase}`;

    // Try environment-specific variable first
    const fundingSeed = process.env[envVarName];

    if (fundingSeed) {
      return fundingSeed;
    }

    if (envName !== 'undeployed') {
      throw new Error(
        `Please provide a funding seed for ${envName} environment by setting up an env varialbe named FUNDING_SEED_${envNameUppercase}`,
      );
    }

    // Default fallback
    const undeployedFundingSeed = '0'.repeat(63) + '1';
    return undeployedFundingSeed;
  }

  /**
   * Retrieves an unshielded address from the test data by property name.
   * @param property - The property name of the unshielded address to retrieve.
   * @returns The unshielded address as a string.
   * @throws Error if the property is not found or undefined for the current environment.
   */
  getUnshieldedAddress(property: string) {
    const envName = env.getCurrentEnvironmentName();
    if (Object.keys(this.unshieldedAddresses).length === 0) {
      const baseDir = `data/static/${envName}`;
      this.unshieldedAddresses = importJsoncData(`${baseDir}/unshielded-addresses.json`) as Record<
        string,
        string
      >;
    }
    if (
      !this.unshieldedAddresses.hasOwnProperty(property) ||
      this.unshieldedAddresses[property] === undefined
    ) {
      throw new Error(
        `Test data provider is missing the unshielded address data for ${property} for ${envName} environment`,
      );
    }
    return this.unshieldedAddresses[property];
  }

  /**
   * Retrieves the custom (non-NIGHT) unshielded token types this environment's chain
   * was last seen holding unspent, from the block-scanner generated
   * `data/static/<env>/unshielded-token-types.jsonc`, strongest candidate first.
   *
   * Returns an empty array instead of throwing when the file is missing: a custom
   * unshielded token is minted by a contract, so no chain starts with one, and a
   * missing file means the environment was never provisioned with such a token — the
   * tests that need it must skip rather than fail as if the indexer were at fault.
   * A file that exists but cannot be read or parsed throws instead, so a broken
   * fixture cannot masquerade as an unprovisioned environment.
   *
   * These are candidates, not guarantees. The fixture records what was unspent when
   * the chain was scanned, so a caller must still probe the live balance and move on
   * to the next candidate (or skip) when a token has since been spent.
   *
   * @returns The hex-encoded token types, empty when this environment has none.
   */
  getCustomUnshieldedTokenTypes(): string[] {
    if (this.customUnshieldedTokenTypes === null) {
      const envName = env.getCurrentEnvironmentName();
      const filePath = `data/static/${envName}/unshielded-token-types.jsonc`;
      let customTokens: CustomUnshieldedToken[] = [];
      try {
        const parsed = importJsoncData(filePath);
        const tokens = (parsed as Record<string, JsonValue>)['custom-tokens'];
        customTokens = Array.isArray(tokens) ? (tokens as unknown as CustomUnshieldedToken[]) : [];
      } catch (error) {
        // A missing file is the "never provisioned" case handled above; anything else is a
        // broken fixture, which must not read as an unprovisioned environment and skip.
        if ((error as { code?: string }).code !== 'ENOENT') {
          throw new Error(`Test data provider cannot read ${filePath}`, { cause: error });
        }
      }
      this.customUnshieldedTokenTypes = customTokens.map((token) => token['token-type']);
    }
    return this.customUnshieldedTokenTypes;
  }

  /**
   * Searches through contracts to find a specific contract action by type.
   * @param actionType - The type of contract action to find (e.g., 'ContractDeploy', 'ContractCall').
   * @returns The contract action object if found, null otherwise.
   * @throws Error if the contract actions file is missing.
   */
  private findContractAction(actionType: string): ContractActionInfo | null {
    // Contracts is an array of contract objects with a contract-actions array
    // NOTE: it could be empty if there are no contracts with all the actions types
    const envName = env.getCurrentEnvironmentName();
    const baseDir = `data/static/${envName}`;
    let contracts: ContractInfo[];
    try {
      contracts = importJsoncData(`${baseDir}/contract-actions.jsonc`) as unknown as ContractInfo[];
    } catch (error) {
      throw new Error(
        `Test data provider is missing the contract actions file for ${envName} environment`,
        { cause: error },
      );
    }

    for (const contract of contracts) {
      const action = contract['contract-actions'].find((a) => a['action-type'] === actionType);
      if (action) {
        return action;
      }
    }
    return null;
  }

  /**
   * Retrieves the block hash associated with a specific contract action type.
   * @param actionType - The type of contract action.
   * @returns A promise that resolves to the block hash.
   * @throws Error if the action type is not found or has no block hash.
   */
  private getBlockData(actionType: string): Promise<string> {
    const action = this.findContractAction(actionType);
    const envName = env.getCurrentEnvironmentName();
    if (action && action['block-hash'] !== undefined) {
      return Promise.resolve(action['block-hash']);
    }
    return Promise.reject(
      new Error(
        `Test data provider missing the block hash for action type ${actionType} in ${envName} environment`,
      ),
    );
  }

  /**
   * Retrieves the block height associated with a specific contract action type.
   * @param actionType - The type of contract action.
   * @returns A promise that resolves to the block height as a number.
   * @throws Error if the action type is not found or has no block height.
   */
  private getBlockHeightOfContractAction(actionType: string): Promise<number> {
    const action = this.findContractAction(actionType);
    const envName = env.getCurrentEnvironmentName();
    if (action && action['block-height'] !== undefined) {
      return Promise.resolve(action['block-height']);
    }
    return Promise.reject(
      new Error(
        `Test data provider is missing the block height for action type ${actionType} in ${envName} environment`,
      ),
    );
  }

  /**
   * Gets a known block hash
   * @returns A promise that resolves to the block hash.
   */
  getKnownBlockHash() {
    return this.getBlockData('ContractDeploy');
  }

  /**
   * Gets the block hash where a contract was deployed.
   * @returns A promise that resolves to the deployment block hash.
   */
  getContractDeployBlockHash() {
    return this.getBlockData('ContractDeploy');
  }

  /**
   * Gets the contract address for the first contract that has an action of the given type.
   * @param actionType - The type of contract action to find.
   * @returns The contract address as a string.
   * @throws Error if no contract with that action type is found.
   */
  getContractAddressForActionType(actionType: string): string {
    const envName = env.getCurrentEnvironmentName();
    const baseDir = `data/static/${envName}`;
    let contracts: ContractInfo[];
    try {
      contracts = importJsoncData(`${baseDir}/contract-actions.jsonc`) as unknown as ContractInfo[];
    } catch (error) {
      throw new Error(
        `Test data provider is missing the contract actions file for ${envName} environment`,
        { cause: error },
      );
    }
    for (const contract of contracts) {
      if (contract['contract-actions'].some((a) => a['action-type'] === actionType)) {
        return contract['contract-address'];
      }
    }
    throw new Error(
      `Test data provider is missing a contract with action type ${actionType} for ${envName} environment`,
    );
  }

  /**
   * Gets the block hash where a contract was updated.
   * @returns A promise that resolves to the update block hash.
   */
  getContractUpdateBlockHash() {
    return this.getBlockData('ContractUpdate');
  }

  /**
   * Gets the block height where a contract was deployed.
   * @returns A promise that resolves to the deployment block height.
   */
  getContractDeployBlockHeight() {
    return this.getBlockHeightOfContractAction('ContractDeploy');
  }

  /**
   * Gets the block height where a contract was called.
   * @returns A promise that resolves to the contract call block height.
   */
  getContractCallBlockHeight() {
    return this.getBlockHeightOfContractAction('ContractCall');
  }

  /**
   * Gets the block height where a contract was updated.
   * @returns A promise that resolves to the update block height.
   */
  getContractUpdateBlockHeight() {
    return this.getBlockHeightOfContractAction('ContractUpdate');
  }

  /**
   * Returns an array of fabricated malformed hash values for negative testing.
   * These include invalid hex strings, incorrect lengths, and other malformed formats.
   * @returns An array of malformed hash strings.
   */
  getFabricatedMalformedHashes() {
    return [
      '0', // half byte
      '000000000000000000000000000000000000000000000000000000000000000G', // Not a valid hex string
      '000000000000000000000000000000000000000000000000000000000000000@', // Not a valid hex string
      '00000000000000000000000000000000000000000000000000000000000062', // 31 bytes (too short)
      '000000000000000000000000000000000000000000000000000000000000000066', // 33 bytes (too long)
    ];
  }

  /**
   * Returns an array of fabricated malformed identifier values for negative testing.
   * These include invalid hex strings and incorrect formats.
   * @returns An array of malformed identifier strings.
   */
  getFabricatedMalformedIdentifiers() {
    return [
      '000000000000000000000000000000000000000000000000000000000000000G', // Not a valid hex string
      '000000000000000000000000000000000000000000000000000000000000000@', // Not a valid hex string
      '0', // Half byte
    ];
  }

  /**
   * Returns an array of fabricated malformed height values for negative testing.
   * These include negative numbers, non-integers, and overflow values.
   * @returns An array of malformed height numbers.
   */
  getFabricatedMalformedHeights() {
    return [
      -1, // negative height
      0.5, // not an integer
      2 ** 32, // 32-bit overflow
    ];
  }

  /**
   * Gets a known contract address from the test data.
   * @returns The contract address as a string.
   * @throws Error if the contract actions file is missing or no contract address is found in the test data.
   */
  getKnownContractAddress(): string {
    const envName = env.getCurrentEnvironmentName();
    const baseDir = `data/static/${envName}`;
    let contracts: ContractInfo[];
    try {
      contracts = importJsoncData(`${baseDir}/contract-actions.jsonc`) as unknown as ContractInfo[];
    } catch (error) {
      throw new Error(
        `Test data provider is missing the contract actions file for ${envName} environment`,
        { cause: error },
      );
    }
    if (contracts.length === 0 || !contracts[0]['contract-address']) {
      throw new Error(
        `Test data provider is missing the known contract address data for ${envName} environment`,
      );
    }
    return contracts[0]['contract-address'];
  }

  /**
   * Returns the contracts known to have emitted public contract events on the
   * current environment's chain, for the contract-event integration tests.
   * @returns A non-empty list of event-emitting contracts.
   * @throws Error if the fixture file is missing or empty for the current
   *         environment, so the data-dependent event assertions skip cleanly.
   */
  getEventEmittingContracts(): EventEmittingContractInfo[] {
    const envName = env.getCurrentEnvironmentName();
    const baseDir = `data/static/${envName}`;
    let contracts: EventEmittingContractInfo[];
    try {
      contracts = importJsoncData(
        `${baseDir}/contract-events.jsonc`,
      ) as unknown as EventEmittingContractInfo[];
    } catch (error) {
      throw new Error(
        `Test data provider is missing the contract events file for ${envName} environment`,
        { cause: error },
      );
    }
    if (contracts.length === 0 || !contracts[0]['contract-address']) {
      throw new Error(
        `Test data provider is missing event-emitting contract data for ${envName} environment`,
      );
    }
    return contracts;
  }

  /**
   * Returns a valid format contract address that doesn't exist in the blockchain.
   * Used for testing non-existent address scenarios.
   * @returns A non-existing contract address string.
   */
  getNonExistingContractAddress() {
    // Return a valid format address that doesn't exist
    return '000200e99d4445695a6244a01ab00d592825e2703c3f9a928f01429561585ce2db1e79';
  }

  /**
   * Returns an array of fabricated malformed contract addresses for negative testing.
   * These include spaces, invalid characters, incorrect lengths, and type mismatches.
   * @returns An array of malformed contract address values.
   */
  getFabricatedMalformedContractAddresses() {
    return [
      ' ', // space
      '0', // too short
      null as unknown as string, // null
      undefined as unknown as string, // undefined
      NaN as unknown as string, // NaN
      Infinity as unknown as string, // Infinity
      -Infinity as unknown as string, // -Infinity
      false as unknown as string, // false
      true as unknown as string, // true
      '000200e99d4445695a6244a01ab00d592825e2703c3f9a928f01429561585ce2db1e7', // too short (63 chars)
      '000200e99d4445695a6244a01ab00d592825e2703c3f9a928f01429561585ce2db1e78a', // too long (65 chars)
      '000200e99d4445695a6244a01ab00d592825e2703c3f9a928f01429561585ce2db1e7g', // invalid hex character
      '000200e99d4445695a6244a01ab00d592825e2703c3f9a928f01429561585ce2db1e7@', // special character
      '000200e99d4445695a6244a01ab00d592825e2703c3f9a928f01429561585ce2db1e7 ', // trailing space
      ' 000200e99d4445695a6244a01ab00d592825e2703c3f9a928f01429561585ce2db1e78', // leading space
      ' 000200e99d4445695a6244a01ab00d592825e2703c3f9a928f01429561585ce2db1e78 ', // leading and trailing space
    ];
  }

  /**
   * Returns boundary value contract addresses for edge case testing.
   * These include all zeros, all ones, and maximum hex values.
   * @returns An array of boundary contract addresses.
   */
  getBoundaryContractAddresses() {
    return [
      '0000000000000000000000000000000000000000000000000000000000000000000000000000', // all zeros
      '0000000000000000000000000000000000000000000000000000000000000000000000000001', // all zeros except first byte
      '1111111111111111111111111111111111111111111111111111111111111111111111111111', // all ones
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff', // highest hex value
    ];
  }

  /**
   * Returns a valid format hash that doesn't exist in the blockchain.
   * Used for testing non-existent hash scenarios.
   * @returns A non-existing hash string (all zeros).
   */
  getNonExistingHash() {
    // Return a valid format hash that doesn't exist (all zeros)
    return '0000000000000000000000000000000000000000000000000000000000000000';
  }

  /**
   * Retrieves a Cardano reward address for a given property.
   * Currently shares the same backing data as stake keys until dedicated reward address fixtures are provided.
   * @param property - The property name to look up.
   * @returns The Cardano reward address as a string.
   */
  getCardanoRewardAddress(property: string) {
    const envName = env.getCurrentEnvironmentName();
    if (Object.keys(this.cardanoRewardAddresses).length === 0) {
      const baseDir = `data/static/${envName}`;
      try {
        this.cardanoRewardAddresses = importJsoncData(
          `${baseDir}/cardano-stake-addresses.jsonc`,
        ) as Record<string, string>;
      } catch (error) {
        throw new Error(
          `Test data provider is missing the cardano stake address file for ${envName} environment`,
          { cause: error },
        );
      }
    }
    if (
      !this.cardanoRewardAddresses.hasOwnProperty(property) ||
      this.cardanoRewardAddresses[property] === undefined
    ) {
      throw new Error(
        `Test data provider is missing the cardano stake address data for ${property} for ${envName} environment`,
      );
    }
    return this.cardanoRewardAddresses[property];
  }

  /**
   * Returns the multi-UTXO candidate snapshots for the current environment.
   * Each entry is a Cardano stake credential whose wallet has multiple
   * backing cNIGHT UTXOs (per-UTXO amounts + total). Loaded lazily from
   * `cardano-stake-addresses.jsonc` under the `multi-utxo` key.
   * @returns The array of candidate snapshots (empty if the fixture has none).
   * @throws Error if the fixture file is missing for the current environment.
   */
  getMultiUtxoCandidates(): MultiUtxoCandidate[] {
    const envName = env.getCurrentEnvironmentName();
    if (this.multiUtxoCandidates === null) {
      const baseDir = `data/static/${envName}`;
      let parsed: JsonValue;
      try {
        parsed = importJsoncData(`${baseDir}/cardano-stake-addresses.jsonc`);
      } catch (error) {
        throw new Error(
          `Test data provider is missing the cardano stake address file for ${envName} environment`,
          { cause: error },
        );
      }
      const candidates = (parsed as JsonObject)['multi-utxo'];
      this.multiUtxoCandidates = Array.isArray(candidates)
        ? (candidates as unknown as MultiUtxoCandidate[])
        : [];
    }
    return this.multiUtxoCandidates;
  }

  /**
   * Gets the contracts known to hold non-zero unshielded token balances on the current
   * environment's chain. Used by the unshieldedBalances regression tests (#1245).
   * @returns An array of token-holding contract entries.
   * @throws Error if the current environment has no token-holding contracts file.
   */
  getTokenHoldingContracts(): TokenHoldingContractInfo[] {
    const envName = env.getCurrentEnvironmentName();
    const baseDir = `data/static/${envName}`;
    let contracts: JsonValue;
    try {
      contracts = importJsoncData(`${baseDir}/token-holding-contracts.jsonc`);
    } catch (error) {
      throw new Error(
        `Test data provider is missing the token holding contracts file for ${envName} environment`,
        { cause: error },
      );
    }
    return Array.isArray(contracts) ? (contracts as unknown as TokenHoldingContractInfo[]) : [];
  }

  /**
   * Returns an array of fabricated malformed Cardano stake keys for negative testing.
   * These include empty strings, invalid hex characters, and special characters.
   * @returns An array of malformed Cardano stake key strings.
   */
  getFabricatedMalformedCardanoRewardAddresss() {
    return [
      '', // empty string
      'G'.repeat(64), // invalid hex characters
      '0123456789abcdef@', // special character
    ];
  }
}

const dataProvider = new TestDataProvider();
export default dataProvider;
