name: CI + E2E

env:
  # Define environment variables for AWS credentials and region
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}

on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  local-environment-tests:
    name: Local Environment Tests
    runs-on: ubuntu-latest-16-core-x64
    permissions:
      pull-requests: write
      packages: read
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
        with:
          submodules: true
      - name: Download mn-cngd
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05  # v1.12
        with:
          repository: 'midnightntwrk/midnight-cnight-generates-dust'
          tag: v0.1.0
          fileName: mn-cngd*linux-amd64.tar.gz
          extract: true
          token: ${{ secrets.MIDNIGHTCI_REPO }}
      - name: Run mn-cngd
        run: |
          ls -lha
          file mn-cngd
          ldd mn-cngd || echo "ldd failed"
          patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 mn-cngd
          sudo apt update
          sudo apt-get install -y liblmdb0 libsodium23
          mkdir -p deps/lib
          cd deps/lib
          curl -L -o libblst.so https://github.com/supranational/blst/releases/download/v0.3.16/libblst.so
          curl -L -o libsecp256k1.so.5 https://github.com/bitcoin-core/secp256k1/releases/download/v0.7.0/libsecp256k1.so.5
          curl -L -o libsodium.so.26 https://github.com/jedisct1/libsodium/releases/download/1.0.20/libsodium.so.26
          cd ../..
          export LD_LIBRARY_PATH=$PWD/deps/lib:$LD_LIBRARY_PATH
          file mn-cngd
          ldd mn-cngd || echo "ldd failed"
          ./mn-cngd --help
      - name: Deploy and test against local environment
        uses: ./.github/actions/local-environment-tests
        with:
          tag: CI
          image: ghcr.io/midnight-ntwrk/midnight-node:0.17.0-dev-18486bc4-amd64
          indexer-api-image: ghcr.io/midnight-ntwrk/indexer-api:18486bc4
          chain-indexer-image: ghcr.io/midnight-ntwrk/chain-indexer:18486bc4
          wallet-indexer-image: ghcr.io/midnight-ntwrk/wallet-indexer:18486bc4
          indexer-tag: 18486bc4
          sha: 18486bc4
          tests: premerge
          ghcr-password: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
