name: +node-e2e-test-remote (qanet)

on:
  workflow_dispatch:
    inputs:
      QA_BRANCH:
        type: string
        description: QA branch to use
        required: false
        default: 'qa-qanet'
      RESET: 
        type: choice
        description: Reset the cache
        required: true
        default: 'false'
        options:
          - true
          - false
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    name: Healthcheck tests
    uses: ./.github/workflows/e2e-tests-remote.yml
    with:
      TEST_ENV_INPUT: qanet
      RESET: ${{ inputs.RESET || 'false' }}
      QA_BRANCH: ${{ inputs.QA_BRANCH || 'qa-qanet' }}
    secrets: inherit
