name: Scan
permissions: {}

on:
  push:
    branches: [main]
    paths-ignore:
      - "changes/**"
  pull_request:
    branches: [main]
  workflow_dispatch: {}   # so you can still run it manually
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
concurrency:
  group: ${{ github.event_name != 'merge_group' && format('{0}-{1}', github.workflow, github.head_ref) || github.run_id }}
  cancel-in-progress: true

env:
  # needed to stop rate limiting of compact download.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1

      - id: guard
        uses: ./.github/actions/tree-cache-guard

      - name: Scan code
        if: steps.guard.outputs.hit != 'true'
        uses: midnightntwrk/upload-sarif-github-action@1101dd4be9e5d1f40cd0d7de4e710284b58f08cf
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/tree-cache-guard/save
        if: steps.guard.outputs.hit != 'true'
        with:
          key: ${{ steps.guard.outputs.key }}
