name: Sign Container Image

on:
  workflow_call:
    inputs:
      image:
        description: 'Full image reference (registry/name:tag)'
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write  # Required for keyless signing

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: MidnightCI
          password: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Sign image
        run: |
          # Get the image digest from registry
          DIGEST=$(docker manifest inspect ${{ inputs.image }} --verbose | jq -r '.Descriptor.digest')

          echo "Signing ${{ inputs.image }} (${DIGEST})"
          cosign sign --yes ${{ inputs.image }}@${DIGEST}
